listening-port=3478
tls-listening-port=5349
alt-listening-port=3479
alt-tls-listening-port=5350

listening-ip=0.0.0.0
relay-ip=0.0.0.0
min-port=49160
max-port=49200

use-auth-secret
static-auth-secret=__REPLACE_WITH_TURN_SHARED_SECRET__
realm=swiip.app

lt-cred-mech

no-multicast-peers
no-cli
no-loopback-peers
fingerprint
mobility
