/* eslint-disable @typescript-eslint/no-require-imports */
/**
 * ÜRETİLMİŞ DOSYA — elle düzenleme.
 * Üreten: scripts/hareket-medya-ice-aktar.mjs
 * Kaynak: free-exercise-db (kamu malı).
 *
 * React Native paketleyicisi değişkenli require() çözemediği için harita statik.
 */

export const HAREKET_GORSELLERI: Record<string, number> = {
  'ab-wheel': require('../../assets/hareketler/ab-wheel.jpg'),
  'arnold-press': require('../../assets/hareketler/arnold-press.jpg'),
  'asili-diz-cekme': require('../../assets/hareketler/asili-diz-cekme.jpg'),
  'ayakta-baldir': require('../../assets/hareketler/ayakta-baldir.jpg'),
  'bant-ile-ayirma': require('../../assets/hareketler/bant-ile-ayirma.jpg'),
  'bant-omuz-rotasyon': require('../../assets/hareketler/bant-omuz-rotasyon.jpg'),
  'barbell-bench-press': require('../../assets/hareketler/barbell-bench-press.jpg'),
  'barbell-curl': require('../../assets/hareketler/barbell-curl.jpg'),
  'barbell-deadlift': require('../../assets/hareketler/barbell-deadlift.jpg'),
  'barbell-omuz-presi': require('../../assets/hareketler/barbell-omuz-presi.jpg'),
  'barbell-row': require('../../assets/hareketler/barbell-row.jpg'),
  'barbell-squat': require('../../assets/hareketler/barbell-squat.jpg'),
  barfiks: require('../../assets/hareketler/barfiks.jpg'),
  'bench-dip': require('../../assets/hareketler/bench-dip.jpg'),
  'biceps-curl': require('../../assets/hareketler/biceps-curl.jpg'),
  'bilek-curl': require('../../assets/hareketler/bilek-curl.jpg'),
  'bulgarian-split-squat': require('../../assets/hareketler/bulgarian-split-squat.jpg'),
  'cekic-curl': require('../../assets/hareketler/cekic-curl.jpg'),
  'ciftci-yuruyusu': require('../../assets/hareketler/ciftci-yuruyusu.jpg'),
  'dead-bug': require('../../assets/hareketler/dead-bug.jpg'),
  'dik-cekis-kablo': require('../../assets/hareketler/dik-cekis-kablo.jpg'),
  'dip-gogus': require('../../assets/hareketler/dip-gogus.jpg'),
  'dip-triceps': require('../../assets/hareketler/dip-triceps.jpg'),
  'dumbbell-baldir': require('../../assets/hareketler/dumbbell-baldir.jpg'),
  'dumbbell-bench-press': require('../../assets/hareketler/dumbbell-bench-press.jpg'),
  'dumbbell-fly': require('../../assets/hareketler/dumbbell-fly.jpg'),
  'dumbbell-row': require('../../assets/hareketler/dumbbell-row.jpg'),
  'egimli-barbell-press': require('../../assets/hareketler/egimli-barbell-press.jpg'),
  'egimli-dumbbell-press': require('../../assets/hareketler/egimli-dumbbell-press.jpg'),
  'egimli-sinav': require('../../assets/hareketler/egimli-sinav.jpg'),
  'ez-bar-curl': require('../../assets/hareketler/ez-bar-curl.jpg'),
  'face-pull': require('../../assets/hareketler/face-pull.jpg'),
  'glute-bridge': require('../../assets/hareketler/glute-bridge.jpg'),
  'goblet-squat': require('../../assets/hareketler/goblet-squat.jpg'),
  'hack-squat': require('../../assets/hareketler/hack-squat.jpg'),
  'hip-thrust': require('../../assets/hareketler/hip-thrust.jpg'),
  hiperekstansiyon: require('../../assets/hareketler/hiperekstansiyon.jpg'),
  'iyi-sabah': require('../../assets/hareketler/iyi-sabah.jpg'),
  'kablo-biceps-curl': require('../../assets/hareketler/kablo-biceps-curl.jpg'),
  'kablo-crunch': require('../../assets/hareketler/kablo-crunch.jpg'),
  'kablo-lateral-raise': require('../../assets/hareketler/kablo-lateral-raise.jpg'),
  'kablo-tek-kol-pullover': require('../../assets/hareketler/kablo-tek-kol-pullover.jpg'),
  'kalca-abduksiyon': require('../../assets/hareketler/kalca-abduksiyon.jpg'),
  'kalca-fleksor-esnetme': require('../../assets/hareketler/kalca-fleksor-esnetme.jpg'),
  'kettlebell-swing': require('../../assets/hareketler/kettlebell-swing.jpg'),
  'kol-cevirme': require('../../assets/hareketler/kol-cevirme.jpg'),
  'kosu-bandi-tempolu': require('../../assets/hareketler/kosu-bandi-tempolu.jpg'),
  'kurek-makinesi': require('../../assets/hareketler/kurek-makinesi.jpg'),
  'kutuya-ciks': require('../../assets/hareketler/kutuya-ciks.jpg'),
  'lat-pulldown': require('../../assets/hareketler/lat-pulldown.jpg'),
  'leg-extension': require('../../assets/hareketler/leg-extension.jpg'),
  'leg-press': require('../../assets/hareketler/leg-press.jpg'),
  lunge: require('../../assets/hareketler/lunge.jpg'),
  'makine-arka-omuz': require('../../assets/hareketler/makine-arka-omuz.jpg'),
  'makine-gogus-presi': require('../../assets/hareketler/makine-gogus-presi.jpg'),
  'makine-hamstring-curl': require('../../assets/hareketler/makine-hamstring-curl.jpg'),
  'makine-lateral-raise': require('../../assets/hareketler/makine-lateral-raise.jpg'),
  'makine-omuz-presi': require('../../assets/hareketler/makine-omuz-presi.jpg'),
  'masa-alti-cekis': require('../../assets/hareketler/masa-alti-cekis.jpg'),
  mekik: require('../../assets/hareketler/mekik.jpg'),
  'merdiven-cikma': require('../../assets/hareketler/merdiven-cikma.jpg'),
  'mountain-climber': require('../../assets/hareketler/mountain-climber.jpg'),
  'omuz-presi-dumbbell': require('../../assets/hareketler/omuz-presi-dumbbell.jpg'),
  'oturarak-baldir': require('../../assets/hareketler/oturarak-baldir.jpg'),
  'overhead-triceps': require('../../assets/hareketler/overhead-triceps.jpg'),
  'pallof-press': require('../../assets/hareketler/pallof-press.jpg'),
  'pec-deck': require('../../assets/hareketler/pec-deck.jpg'),
  plank: require('../../assets/hareketler/plank.jpg'),
  'preacher-curl': require('../../assets/hareketler/preacher-curl.jpg'),
  'romanian-deadlift': require('../../assets/hareketler/romanian-deadlift.jpg'),
  'sabit-bisiklet': require('../../assets/hareketler/sabit-bisiklet.jpg'),
  'shrug-barbell': require('../../assets/hareketler/shrug-barbell.jpg'),
  'shrug-dumbbell': require('../../assets/hareketler/shrug-dumbbell.jpg'),
  sinav: require('../../assets/hareketler/sinav.jpg'),
  'smith-gogus-presi': require('../../assets/hareketler/smith-gogus-presi.jpg'),
  'step-up': require('../../assets/hareketler/step-up.jpg'),
  'sumo-deadlift': require('../../assets/hareketler/sumo-deadlift.jpg'),
  'svend-press': require('../../assets/hareketler/svend-press.jpg'),
  't-bar-row': require('../../assets/hareketler/t-bar-row.jpg'),
  'ters-curl': require('../../assets/hareketler/ters-curl.jpg'),
  'ters-fly-dumbbell': require('../../assets/hareketler/ters-fly-dumbbell.jpg'),
  'ters-kavrama-barfiks': require('../../assets/hareketler/ters-kavrama-barfiks.jpg'),
  'ters-kavrama-lat-pulldown': require('../../assets/hareketler/ters-kavrama-lat-pulldown.jpg'),
  'ters-mekik': require('../../assets/hareketler/ters-mekik.jpg'),
  'trap-bar-deadlift': require('../../assets/hareketler/trap-bar-deadlift.jpg'),
  'triceps-halat-pushdown': require('../../assets/hareketler/triceps-halat-pushdown.jpg'),
  'triceps-pushdown': require('../../assets/hareketler/triceps-pushdown.jpg'),
  'vucut-agirligi-baldir': require('../../assets/hareketler/vucut-agirligi-baldir.jpg'),
  'vucut-agirligi-squat': require('../../assets/hareketler/vucut-agirligi-squat.jpg'),
  'yan-egilme-dumbbell': require('../../assets/hareketler/yan-egilme-dumbbell.jpg'),
  'yan-lateral-raise': require('../../assets/hareketler/yan-lateral-raise.jpg'),
  'yardimli-barfiks': require('../../assets/hareketler/yardimli-barfiks.jpg'),
  'yatarak-triceps-ekstansiyon': require('../../assets/hareketler/yatarak-triceps-ekstansiyon.jpg'),
};

/** Görseli olmayan hareket için undefined döner; ekran bunu boş alanla karşılar. */
export function hareketGorseli(id: string): number | undefined {
  return HAREKET_GORSELLERI[id];
}
