/**
 * Başlangıç besin veritabanı — Türk mutfağının çekirdeği ve ev ölçü birimleri.
 *
 * Kaynak notu: değerler TürKomp ve USDA bileşim tablolarının kamuya açık ortalamalarıyla
 * uyumlu tutuldu. TürKomp'un kullanım koşulları yazılı teyit edildikten sonra tam içe
 * aktarma yapılacak (F5.4); bu set o zamana kadar arama ve manuel girişi çalışır kılar.
 *
 * Kritik kural: veritabanı MİKTAR vermez, BİLEŞİM verir. Toplam = miktar × bileşim.
 * Aynı yemek her zaman aynı makroyu üretir — EatBetter'ın en beğenilen şikâyetinin panzehiri.
 */

export interface PorsiyonTanimi {
  id: string;
  ad: string;
  gram: number;
}

export interface BesinTohumu {
  name_tr: string;
  name_en?: string;
  per_100g: {
    kalori: number;
    protein_g: number;
    yag_g: number;
    karbonhidrat_g: number;
    lif_g: number;
  };
  portions: PorsiyonTanimi[];
  source: 'turkomp' | 'openfoodfacts' | 'bizim' | 'kullanici' | 'zincir';
  verified: boolean;
}

/** Türkiye'de fiilen kullanılan ev ölçüleri. Gram tek başına kimseye bir şey ifade etmiyor. */
export const EV_OLCULERI = {
  kase: (gram: number): PorsiyonTanimi => ({ id: 'kase', ad: '1 kase', gram }),
  tabak: (gram: number): PorsiyonTanimi => ({ id: 'tabak', ad: '1 tabak', gram }),
  kepce: (gram: number): PorsiyonTanimi => ({ id: 'kepce', ad: '1 kepçe', gram }),
  yemekKasigi: (gram: number): PorsiyonTanimi => ({
    id: 'yemek_kasigi',
    ad: '1 yemek kaşığı',
    gram,
  }),
  cayKasigi: (gram: number): PorsiyonTanimi => ({ id: 'cay_kasigi', ad: '1 çay kaşığı', gram }),
  dilim: (gram: number): PorsiyonTanimi => ({ id: 'dilim', ad: '1 dilim', gram }),
  avuc: (gram: number): PorsiyonTanimi => ({ id: 'avuc', ad: '1 avuç', gram }),
  adet: (gram: number): PorsiyonTanimi => ({ id: 'adet', ad: '1 adet', gram }),
  bardak: (gram: number): PorsiyonTanimi => ({ id: 'bardak', ad: '1 su bardağı', gram }),
  porsiyon: (gram: number): PorsiyonTanimi => ({ id: 'porsiyon', ad: '1 porsiyon', gram }),
} as const;

const { kase, tabak, kepce, yemekKasigi, cayKasigi, dilim, avuc, adet, bardak, porsiyon } =
  EV_OLCULERI;

export const BESIN_TOHUMU: BesinTohumu[] = [
  // --- Ham gıda: protein kaynakları ---
  {
    name_tr: 'Tavuk göğsü, pişmiş',
    name_en: 'Chicken breast, cooked',
    per_100g: { kalori: 165, protein_g: 31, yag_g: 3.6, karbonhidrat_g: 0, lif_g: 0 },
    portions: [porsiyon(150), avuc(100), adet(180)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Tavuk but, pişmiş',
    per_100g: { kalori: 209, protein_g: 26, yag_g: 11, karbonhidrat_g: 0, lif_g: 0 },
    portions: [porsiyon(150), adet(120)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Dana kıyma, %15 yağlı, pişmiş',
    per_100g: { kalori: 250, protein_g: 26, yag_g: 16, karbonhidrat_g: 0, lif_g: 0 },
    portions: [porsiyon(120), yemekKasigi(20)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Dana bonfile, ızgara',
    per_100g: { kalori: 187, protein_g: 30, yag_g: 7, karbonhidrat_g: 0, lif_g: 0 },
    portions: [porsiyon(150)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Kuzu pirzola, ızgara',
    per_100g: { kalori: 282, protein_g: 25, yag_g: 20, karbonhidrat_g: 0, lif_g: 0 },
    portions: [adet(60), porsiyon(180)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Hamsi, tavada',
    per_100g: { kalori: 210, protein_g: 20, yag_g: 14, karbonhidrat_g: 2, lif_g: 0 },
    portions: [porsiyon(150), adet(15)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Somon, fırında',
    per_100g: { kalori: 208, protein_g: 22, yag_g: 13, karbonhidrat_g: 0, lif_g: 0 },
    portions: [porsiyon(150)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Levrek, ızgara',
    per_100g: { kalori: 124, protein_g: 24, yag_g: 3, karbonhidrat_g: 0, lif_g: 0 },
    portions: [porsiyon(200), adet(250)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Yumurta, haşlanmış',
    per_100g: { kalori: 155, protein_g: 13, yag_g: 11, karbonhidrat_g: 1.1, lif_g: 0 },
    portions: [adet(50)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Yumurta akı',
    per_100g: { kalori: 52, protein_g: 11, yag_g: 0.2, karbonhidrat_g: 0.7, lif_g: 0 },
    portions: [adet(33)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Ton balığı, suda, konserve',
    per_100g: { kalori: 116, protein_g: 26, yag_g: 1, karbonhidrat_g: 0, lif_g: 0 },
    portions: [adet(160), porsiyon(80)],
    source: 'openfoodfacts',
    verified: true,
  },

  // --- Süt ve süt ürünleri ---
  {
    name_tr: 'Süt, yarım yağlı',
    per_100g: { kalori: 50, protein_g: 3.4, yag_g: 1.6, karbonhidrat_g: 4.8, lif_g: 0 },
    portions: [bardak(200), kase(250)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Yoğurt, yarım yağlı',
    per_100g: { kalori: 63, protein_g: 3.5, yag_g: 3.3, karbonhidrat_g: 4.7, lif_g: 0 },
    portions: [kase(200), yemekKasigi(25), bardak(200)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Süzme yoğurt',
    per_100g: { kalori: 97, protein_g: 10, yag_g: 5, karbonhidrat_g: 3.6, lif_g: 0 },
    portions: [kase(200), yemekKasigi(25)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Beyaz peynir, yarım yağlı',
    per_100g: { kalori: 240, protein_g: 17, yag_g: 18, karbonhidrat_g: 2, lif_g: 0 },
    portions: [dilim(30), avuc(50)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Kaşar peyniri',
    per_100g: { kalori: 350, protein_g: 25, yag_g: 27, karbonhidrat_g: 2, lif_g: 0 },
    portions: [dilim(25)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Ayran',
    per_100g: { kalori: 36, protein_g: 1.7, yag_g: 1.8, karbonhidrat_g: 3.2, lif_g: 0 },
    portions: [bardak(200), adet(300)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Lor peyniri',
    per_100g: { kalori: 98, protein_g: 12, yag_g: 4, karbonhidrat_g: 3, lif_g: 0 },
    portions: [yemekKasigi(25), kase(150)],
    source: 'turkomp',
    verified: true,
  },

  // --- Tahıl ve baklagil ---
  {
    name_tr: 'Pirinç pilavı',
    per_100g: { kalori: 160, protein_g: 3, yag_g: 3.5, karbonhidrat_g: 29, lif_g: 0.5 },
    portions: [kepce(90), kase(180), tabak(250), yemekKasigi(30)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Bulgur pilavı',
    per_100g: { kalori: 143, protein_g: 4, yag_g: 3, karbonhidrat_g: 25, lif_g: 4 },
    portions: [kepce(90), kase(180), tabak(250)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Makarna, haşlanmış',
    per_100g: { kalori: 158, protein_g: 5.8, yag_g: 0.9, karbonhidrat_g: 31, lif_g: 1.8 },
    portions: [kase(200), tabak(250)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Ekmek, beyaz',
    per_100g: { kalori: 265, protein_g: 9, yag_g: 3.2, karbonhidrat_g: 49, lif_g: 2.7 },
    portions: [dilim(30)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Ekmek, tam buğday',
    per_100g: { kalori: 247, protein_g: 13, yag_g: 3.4, karbonhidrat_g: 41, lif_g: 7 },
    portions: [dilim(30)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Yulaf ezmesi, kuru',
    per_100g: { kalori: 379, protein_g: 13, yag_g: 6.5, karbonhidrat_g: 67, lif_g: 10 },
    portions: [yemekKasigi(10), bardak(80), kase(50)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Kuru fasulye yemeği',
    per_100g: { kalori: 127, protein_g: 7, yag_g: 3.5, karbonhidrat_g: 17, lif_g: 6 },
    portions: [kepce(120), kase(220), tabak(280)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Nohut yemeği',
    per_100g: { kalori: 135, protein_g: 7, yag_g: 4, karbonhidrat_g: 18, lif_g: 5.5 },
    portions: [kepce(120), kase(220)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Mercimek çorbası',
    per_100g: { kalori: 65, protein_g: 3.2, yag_g: 2, karbonhidrat_g: 9, lif_g: 2 },
    portions: [kase(250), kepce(100)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Kırmızı mercimek, kuru',
    per_100g: { kalori: 352, protein_g: 25, yag_g: 1.1, karbonhidrat_g: 60, lif_g: 11 },
    portions: [bardak(190), yemekKasigi(15)],
    source: 'turkomp',
    verified: true,
  },

  // --- Pişmiş Türk yemekleri (biz gireriz) ---
  {
    name_tr: 'İzmir köfte',
    per_100g: { kalori: 168, protein_g: 12, yag_g: 11, karbonhidrat_g: 6, lif_g: 1.2 },
    portions: [porsiyon(250), adet(45)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Izgara köfte',
    per_100g: { kalori: 240, protein_g: 19, yag_g: 17, karbonhidrat_g: 3, lif_g: 0.3 },
    portions: [adet(40), porsiyon(160)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Karnıyarık',
    per_100g: { kalori: 128, protein_g: 5, yag_g: 9, karbonhidrat_g: 7, lif_g: 3 },
    portions: [adet(200), porsiyon(250)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Menemen',
    per_100g: { kalori: 118, protein_g: 6, yag_g: 8.5, karbonhidrat_g: 4, lif_g: 1.2 },
    portions: [porsiyon(250), tabak(300)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Mantı, yoğurtlu',
    per_100g: { kalori: 208, protein_g: 8, yag_g: 9, karbonhidrat_g: 24, lif_g: 1.4 },
    portions: [porsiyon(250), kase(200)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Zeytinyağlı taze fasulye',
    per_100g: { kalori: 71, protein_g: 1.9, yag_g: 5, karbonhidrat_g: 5, lif_g: 3 },
    portions: [kepce(110), kase(200)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Etli türlü',
    per_100g: { kalori: 96, protein_g: 6, yag_g: 5, karbonhidrat_g: 7, lif_g: 2.2 },
    portions: [kepce(120), kase(220)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Tavuk sote',
    per_100g: { kalori: 142, protein_g: 17, yag_g: 6, karbonhidrat_g: 5, lif_g: 1 },
    portions: [porsiyon(200), kepce(110)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Lahmacun',
    per_100g: { kalori: 245, protein_g: 11, yag_g: 8, karbonhidrat_g: 33, lif_g: 2 },
    portions: [adet(120)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Pide, kıymalı',
    per_100g: { kalori: 268, protein_g: 12, yag_g: 10, karbonhidrat_g: 33, lif_g: 1.8 },
    portions: [adet(300), dilim(50)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Simit',
    per_100g: { kalori: 322, protein_g: 10, yag_g: 6, karbonhidrat_g: 57, lif_g: 3 },
    portions: [adet(100)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Börek, peynirli',
    per_100g: { kalori: 296, protein_g: 9, yag_g: 18, karbonhidrat_g: 25, lif_g: 1.2 },
    portions: [dilim(120), porsiyon(150)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Çiğ köfte, etsiz',
    per_100g: { kalori: 180, protein_g: 5, yag_g: 5, karbonhidrat_g: 29, lif_g: 5 },
    portions: [adet(30), porsiyon(150)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Cacık',
    per_100g: { kalori: 42, protein_g: 2.4, yag_g: 2.4, karbonhidrat_g: 3, lif_g: 0.4 },
    portions: [kase(200), kepce(100)],
    source: 'bizim',
    verified: true,
  },

  // --- Sebze ve meyve ---
  {
    name_tr: 'Domates',
    per_100g: { kalori: 18, protein_g: 0.9, yag_g: 0.2, karbonhidrat_g: 3.9, lif_g: 1.2 },
    portions: [adet(120), dilim(20)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Salatalık',
    per_100g: { kalori: 15, protein_g: 0.7, yag_g: 0.1, karbonhidrat_g: 3.6, lif_g: 0.5 },
    portions: [adet(150)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Ispanak, haşlanmış',
    per_100g: { kalori: 23, protein_g: 3, yag_g: 0.4, karbonhidrat_g: 3.8, lif_g: 2.4 },
    portions: [kase(180), avuc(50)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Brokoli, haşlanmış',
    per_100g: { kalori: 35, protein_g: 2.4, yag_g: 0.4, karbonhidrat_g: 7, lif_g: 3.3 },
    portions: [kase(150), avuc(50)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Patates, haşlanmış',
    per_100g: { kalori: 87, protein_g: 2, yag_g: 0.1, karbonhidrat_g: 20, lif_g: 1.8 },
    portions: [adet(150), kase(180)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Patates kızartması',
    per_100g: { kalori: 312, protein_g: 3.4, yag_g: 15, karbonhidrat_g: 41, lif_g: 3.8 },
    portions: [porsiyon(150), avuc(50)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Muz',
    per_100g: { kalori: 89, protein_g: 1.1, yag_g: 0.3, karbonhidrat_g: 23, lif_g: 2.6 },
    portions: [adet(120)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Elma',
    per_100g: { kalori: 52, protein_g: 0.3, yag_g: 0.2, karbonhidrat_g: 14, lif_g: 2.4 },
    portions: [adet(180)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Portakal',
    per_100g: { kalori: 47, protein_g: 0.9, yag_g: 0.1, karbonhidrat_g: 12, lif_g: 2.4 },
    portions: [adet(180)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Karpuz',
    per_100g: { kalori: 30, protein_g: 0.6, yag_g: 0.2, karbonhidrat_g: 8, lif_g: 0.4 },
    portions: [dilim(280)],
    source: 'turkomp',
    verified: true,
  },

  // --- Yağ ve kuruyemiş ---
  {
    name_tr: 'Zeytinyağı',
    per_100g: { kalori: 884, protein_g: 0, yag_g: 100, karbonhidrat_g: 0, lif_g: 0 },
    portions: [yemekKasigi(13), cayKasigi(5)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Tereyağı',
    per_100g: { kalori: 717, protein_g: 0.9, yag_g: 81, karbonhidrat_g: 0.1, lif_g: 0 },
    portions: [yemekKasigi(14), cayKasigi(5)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Ceviz içi',
    per_100g: { kalori: 654, protein_g: 15, yag_g: 65, karbonhidrat_g: 14, lif_g: 6.7 },
    portions: [avuc(30), adet(5)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Badem',
    per_100g: { kalori: 579, protein_g: 21, yag_g: 50, karbonhidrat_g: 22, lif_g: 12.5 },
    portions: [avuc(30), adet(1.2)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Fındık',
    per_100g: { kalori: 628, protein_g: 15, yag_g: 61, karbonhidrat_g: 17, lif_g: 9.7 },
    portions: [avuc(30)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Zeytin, siyah',
    per_100g: { kalori: 115, protein_g: 0.8, yag_g: 11, karbonhidrat_g: 6, lif_g: 3.2 },
    portions: [adet(4), avuc(30)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Tahin',
    per_100g: { kalori: 595, protein_g: 17, yag_g: 54, karbonhidrat_g: 21, lif_g: 9 },
    portions: [yemekKasigi(15), cayKasigi(6)],
    source: 'turkomp',
    verified: true,
  },

  // --- Takviye ve hazır ürün ---
  {
    name_tr: 'Whey protein tozu',
    per_100g: { kalori: 380, protein_g: 78, yag_g: 5, karbonhidrat_g: 6, lif_g: 1 },
    portions: [{ id: 'olcek', ad: '1 ölçek', gram: 30 }],
    source: 'openfoodfacts',
    verified: true,
  },
  {
    name_tr: 'Bal',
    per_100g: { kalori: 304, protein_g: 0.3, yag_g: 0, karbonhidrat_g: 82, lif_g: 0.2 },
    portions: [yemekKasigi(21), cayKasigi(7)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Reçel, vişne',
    per_100g: { kalori: 278, protein_g: 0.4, yag_g: 0.1, karbonhidrat_g: 69, lif_g: 1 },
    portions: [yemekKasigi(20), cayKasigi(7)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Baklava',
    per_100g: { kalori: 428, protein_g: 6, yag_g: 24, karbonhidrat_g: 48, lif_g: 1.5 },
    portions: [dilim(60), porsiyon(120)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Sütlaç',
    per_100g: { kalori: 143, protein_g: 3.4, yag_g: 3, karbonhidrat_g: 25, lif_g: 0.2 },
    portions: [kase(150)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Çay, şekersiz',
    per_100g: { kalori: 1, protein_g: 0, yag_g: 0, karbonhidrat_g: 0.3, lif_g: 0 },
    portions: [bardak(100)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Türk kahvesi, şekersiz',
    per_100g: { kalori: 2, protein_g: 0.1, yag_g: 0, karbonhidrat_g: 0.3, lif_g: 0 },
    portions: [{ id: 'fincan', ad: '1 fincan', gram: 70 }],
    source: 'turkomp',
    verified: true,
  },

  // --- Çorbalar ---
  {
    name_tr: 'Ezogelin çorbası',
    per_100g: { kalori: 71, protein_g: 3.4, yag_g: 2.2, karbonhidrat_g: 9.5, lif_g: 1.6 },
    portions: [kase(250), kepce(120)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Yayla çorbası',
    per_100g: { kalori: 67, protein_g: 3, yag_g: 2.6, karbonhidrat_g: 8, lif_g: 0.4 },
    portions: [kase(250), kepce(120)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Tarhana çorbası',
    per_100g: { kalori: 71, protein_g: 3.2, yag_g: 1.8, karbonhidrat_g: 10.5, lif_g: 1.2 },
    portions: [kase(250), kepce(120)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Domates çorbası',
    per_100g: { kalori: 67, protein_g: 2, yag_g: 2.8, karbonhidrat_g: 8.5, lif_g: 1 },
    portions: [kase(250), kepce(120)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Tavuk suyu çorba, şehriyeli',
    per_100g: { kalori: 59, protein_g: 3.6, yag_g: 1.6, karbonhidrat_g: 7.5, lif_g: 0.3 },
    portions: [kase(250), kepce(120)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'İşkembe çorbası',
    per_100g: { kalori: 76, protein_g: 5.5, yag_g: 4, karbonhidrat_g: 4.5, lif_g: 0.2 },
    portions: [kase(250)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Düğün çorbası',
    per_100g: { kalori: 84, protein_g: 4, yag_g: 4.5, karbonhidrat_g: 7, lif_g: 0.4 },
    portions: [kase(250)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Brokoli çorbası',
    per_100g: { kalori: 61, protein_g: 2.6, yag_g: 3, karbonhidrat_g: 6, lif_g: 1.8 },
    portions: [kase(250)],
    source: 'bizim',
    verified: true,
  },

  // --- Etli yemekler ---
  {
    name_tr: 'Tas kebabı',
    per_100g: { kalori: 148, protein_g: 13, yag_g: 8, karbonhidrat_g: 6, lif_g: 1 },
    portions: [porsiyon(250), kepce(130)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Etli güveç',
    per_100g: { kalori: 135, protein_g: 11, yag_g: 7, karbonhidrat_g: 7, lif_g: 1.6 },
    portions: [porsiyon(250)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Orman kebabı',
    per_100g: { kalori: 158, protein_g: 12.5, yag_g: 8.5, karbonhidrat_g: 8, lif_g: 1.4 },
    portions: [porsiyon(250)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Çoban kavurma',
    per_100g: { kalori: 188, protein_g: 17, yag_g: 12, karbonhidrat_g: 3, lif_g: 0.8 },
    portions: [porsiyon(200)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Tavuk şiş, ızgara',
    per_100g: { kalori: 170, protein_g: 26, yag_g: 6.5, karbonhidrat_g: 2, lif_g: 0.3 },
    portions: [porsiyon(180), adet(90)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Adana kebap',
    per_100g: { kalori: 256, protein_g: 17, yag_g: 20, karbonhidrat_g: 2, lif_g: 0.4 },
    portions: [porsiyon(180)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Urfa kebap',
    per_100g: { kalori: 240, protein_g: 17.5, yag_g: 18, karbonhidrat_g: 2, lif_g: 0.4 },
    portions: [porsiyon(180)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Et döner',
    per_100g: { kalori: 245, protein_g: 21, yag_g: 17, karbonhidrat_g: 2, lif_g: 0.2 },
    portions: [porsiyon(150)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Tavuk döner',
    per_100g: { kalori: 181, protein_g: 22, yag_g: 9, karbonhidrat_g: 3, lif_g: 0.2 },
    portions: [porsiyon(150)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'İskender kebap',
    per_100g: { kalori: 260, protein_g: 13, yag_g: 16, karbonhidrat_g: 16, lif_g: 1 },
    portions: [porsiyon(350)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Kadınbudu köfte',
    per_100g: { kalori: 230, protein_g: 14, yag_g: 14, karbonhidrat_g: 12, lif_g: 0.6 },
    portions: [adet(70), porsiyon(210)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Etli kuru fasulye',
    per_100g: { kalori: 131, protein_g: 8.5, yag_g: 5, karbonhidrat_g: 13, lif_g: 5.5 },
    portions: [kepce(130), kase(250)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Etli nohut yemeği',
    per_100g: { kalori: 128, protein_g: 8, yag_g: 4.5, karbonhidrat_g: 14, lif_g: 5 },
    portions: [kepce(130), kase(250)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Fırın tavuk but',
    per_100g: { kalori: 206, protein_g: 24, yag_g: 12, karbonhidrat_g: 0.5, lif_g: 0 },
    portions: [adet(150)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Hünkar beğendi',
    per_100g: { kalori: 177, protein_g: 10.5, yag_g: 11, karbonhidrat_g: 9, lif_g: 2.4 },
    portions: [porsiyon(280)],
    source: 'bizim',
    verified: true,
  },

  // --- Zeytinyağlılar ---
  {
    name_tr: 'İmambayıldı',
    per_100g: { kalori: 120, protein_g: 1.8, yag_g: 9, karbonhidrat_g: 8, lif_g: 3.4 },
    portions: [adet(200), porsiyon(250)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Zeytinyağlı enginar',
    per_100g: { kalori: 106, protein_g: 2.2, yag_g: 7, karbonhidrat_g: 8.5, lif_g: 4.5 },
    portions: [adet(130)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Barbunya pilaki',
    per_100g: { kalori: 123, protein_g: 5.5, yag_g: 5, karbonhidrat_g: 14, lif_g: 5 },
    portions: [kepce(120), kase(220)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Zeytinyağlı yaprak sarma',
    per_100g: { kalori: 141, protein_g: 2.4, yag_g: 7.5, karbonhidrat_g: 16, lif_g: 2.6 },
    portions: [adet(30), porsiyon(180)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Kabak mücver',
    per_100g: { kalori: 149, protein_g: 5, yag_g: 9, karbonhidrat_g: 12, lif_g: 1.6 },
    portions: [adet(60), porsiyon(180)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Zeytinyağlı pırasa',
    per_100g: { kalori: 89, protein_g: 1.8, yag_g: 5.5, karbonhidrat_g: 8, lif_g: 2.8 },
    portions: [kepce(120), kase(220)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Zeytinyağlı kereviz',
    per_100g: { kalori: 79, protein_g: 1.4, yag_g: 5, karbonhidrat_g: 7, lif_g: 2.2 },
    portions: [kepce(120), kase(220)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Zeytinyağlı bakla',
    per_100g: { kalori: 102, protein_g: 4, yag_g: 5.5, karbonhidrat_g: 9, lif_g: 4 },
    portions: [kepce(120)],
    source: 'bizim',
    verified: true,
  },

  // --- Sebze yemekleri ---
  {
    name_tr: 'Sebze türlü',
    per_100g: { kalori: 81, protein_g: 2.2, yag_g: 4.5, karbonhidrat_g: 8, lif_g: 2.6 },
    portions: [kepce(130), kase(250)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Ispanak yemeği',
    per_100g: { kalori: 68, protein_g: 3, yag_g: 4, karbonhidrat_g: 5, lif_g: 2.6 },
    portions: [kepce(130), kase(250)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Kabak yemeği, etli',
    per_100g: { kalori: 87, protein_g: 5.5, yag_g: 5, karbonhidrat_g: 5, lif_g: 1.6 },
    portions: [kepce(130)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Patlıcan musakka',
    per_100g: { kalori: 135, protein_g: 6.5, yag_g: 9, karbonhidrat_g: 7, lif_g: 2.8 },
    portions: [porsiyon(250)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Fırında sebze',
    per_100g: { kalori: 80, protein_g: 2, yag_g: 4, karbonhidrat_g: 9, lif_g: 3 },
    portions: [porsiyon(220)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Biber dolma, etli',
    per_100g: { kalori: 126, protein_g: 5, yag_g: 6, karbonhidrat_g: 13, lif_g: 1.8 },
    portions: [adet(120)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Lahana sarma, etli',
    per_100g: { kalori: 116, protein_g: 4.5, yag_g: 5.5, karbonhidrat_g: 12, lif_g: 2.2 },
    portions: [adet(45), porsiyon(225)],
    source: 'bizim',
    verified: true,
  },

  // --- Pilav ve makarna ---
  {
    name_tr: 'Şehriyeli pirinç pilavı',
    per_100g: { kalori: 166, protein_g: 3.4, yag_g: 4.5, karbonhidrat_g: 28, lif_g: 0.8 },
    portions: [kepce(120), kase(200)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Nohutlu pilav',
    per_100g: { kalori: 166, protein_g: 4.5, yag_g: 4.5, karbonhidrat_g: 27, lif_g: 2 },
    portions: [kepce(120), kase(200)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Kuskus',
    per_100g: { kalori: 130, protein_g: 4, yag_g: 2.5, karbonhidrat_g: 23, lif_g: 1.6 },
    portions: [kepce(120)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Makarna, domates soslu',
    per_100g: { kalori: 150, protein_g: 4.5, yag_g: 3.5, karbonhidrat_g: 25, lif_g: 1.6 },
    portions: [kase(220), tabak(300)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Fırın makarna',
    per_100g: { kalori: 192, protein_g: 8, yag_g: 8, karbonhidrat_g: 22, lif_g: 1.2 },
    portions: [porsiyon(250)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Erişte',
    per_100g: { kalori: 155, protein_g: 5, yag_g: 3, karbonhidrat_g: 27, lif_g: 1.4 },
    portions: [kase(200)],
    source: 'bizim',
    verified: true,
  },

  // --- Baklagil ---
  {
    name_tr: 'Nohut yemeği, etsiz',
    per_100g: { kalori: 109, protein_g: 5.5, yag_g: 3, karbonhidrat_g: 15, lif_g: 5 },
    portions: [kepce(130), kase(250)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Kuru fasulye, etsiz',
    per_100g: { kalori: 107, protein_g: 6, yag_g: 3, karbonhidrat_g: 14, lif_g: 6 },
    portions: [kepce(130), kase(250)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Mercimek yemeği',
    per_100g: { kalori: 111, protein_g: 6, yag_g: 3, karbonhidrat_g: 15, lif_g: 5.5 },
    portions: [kepce(130)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Barbunya yemeği',
    per_100g: { kalori: 110, protein_g: 5.5, yag_g: 3.5, karbonhidrat_g: 14, lif_g: 5.5 },
    portions: [kepce(130)],
    source: 'bizim',
    verified: true,
  },

  // --- Hamur işi ---
  {
    name_tr: 'Su böreği',
    per_100g: { kalori: 235, protein_g: 8, yag_g: 11, karbonhidrat_g: 26, lif_g: 1 },
    portions: [dilim(120), porsiyon(180)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Sigara böreği',
    per_100g: { kalori: 290, protein_g: 8.5, yag_g: 16, karbonhidrat_g: 28, lif_g: 1.2 },
    portions: [adet(35)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Poğaça, peynirli',
    per_100g: { kalori: 292, protein_g: 7.5, yag_g: 14, karbonhidrat_g: 34, lif_g: 1.4 },
    portions: [adet(80)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Açma',
    per_100g: { kalori: 298, protein_g: 7, yag_g: 10, karbonhidrat_g: 45, lif_g: 1.8 },
    portions: [adet(90)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Gözleme, peynirli',
    per_100g: { kalori: 237, protein_g: 9, yag_g: 9, karbonhidrat_g: 30, lif_g: 1.8 },
    portions: [adet(150), porsiyon(200)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Kaşarlı tost',
    per_100g: { kalori: 281, protein_g: 13, yag_g: 13, karbonhidrat_g: 28, lif_g: 1.6 },
    portions: [adet(150)],
    source: 'bizim',
    verified: true,
  },

  // --- Kahvaltılık ---
  {
    name_tr: 'Sucuklu yumurta',
    per_100g: { kalori: 238, protein_g: 13, yag_g: 20, karbonhidrat_g: 1.5, lif_g: 0.1 },
    portions: [porsiyon(180)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Omlet, sade',
    per_100g: { kalori: 156, protein_g: 11, yag_g: 12, karbonhidrat_g: 1, lif_g: 0 },
    portions: [porsiyon(150)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Peynirli omlet',
    per_100g: { kalori: 194, protein_g: 13.5, yag_g: 15, karbonhidrat_g: 1.2, lif_g: 0 },
    portions: [porsiyon(160)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Bal ve kaymak',
    per_100g: { kalori: 370, protein_g: 3, yag_g: 22, karbonhidrat_g: 40, lif_g: 0.2 },
    portions: [porsiyon(60)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Zeytin ezmesi',
    per_100g: { kalori: 202, protein_g: 1.5, yag_g: 20, karbonhidrat_g: 4, lif_g: 3 },
    portions: [yemekKasigi(15)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Kuymak / muhlama',
    per_100g: { kalori: 294, protein_g: 12, yag_g: 22, karbonhidrat_g: 12, lif_g: 0.6 },
    portions: [porsiyon(180)],
    source: 'bizim',
    verified: true,
  },

  // --- Deniz ürünleri ---
  {
    name_tr: 'Hamsi tava',
    per_100g: { kalori: 230, protein_g: 18, yag_g: 14, karbonhidrat_g: 8, lif_g: 0.4 },
    portions: [porsiyon(180)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Somon, ızgara',
    per_100g: { kalori: 213, protein_g: 24, yag_g: 13, karbonhidrat_g: 0, lif_g: 0 },
    portions: [porsiyon(180)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Karides, haşlanmış',
    per_100g: { kalori: 101, protein_g: 22, yag_g: 1.2, karbonhidrat_g: 0.5, lif_g: 0 },
    portions: [porsiyon(120)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Ton balığı, suda',
    per_100g: { kalori: 105, protein_g: 24, yag_g: 1, karbonhidrat_g: 0, lif_g: 0 },
    portions: [porsiyon(80), adet(160)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Sardalya, konserve',
    per_100g: { kalori: 174, protein_g: 21, yag_g: 10, karbonhidrat_g: 0, lif_g: 0 },
    portions: [porsiyon(90)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Midye dolma',
    per_100g: { kalori: 139, protein_g: 5.5, yag_g: 5, karbonhidrat_g: 18, lif_g: 1 },
    portions: [adet(25)],
    source: 'bizim',
    verified: true,
  },

  // --- Salata ve meze ---
  {
    name_tr: 'Çoban salata',
    per_100g: { kalori: 59, protein_g: 1.2, yag_g: 4, karbonhidrat_g: 4.5, lif_g: 1.6 },
    portions: [kase(200), tabak(250)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Gavurdağı salata',
    per_100g: { kalori: 108, protein_g: 3, yag_g: 8, karbonhidrat_g: 6, lif_g: 2 },
    portions: [kase(200)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Haydari',
    per_100g: { kalori: 121, protein_g: 6, yag_g: 9, karbonhidrat_g: 4, lif_g: 0.4 },
    portions: [yemekKasigi(25), porsiyon(80)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Acılı ezme',
    per_100g: { kalori: 75, protein_g: 1.4, yag_g: 5, karbonhidrat_g: 6, lif_g: 2 },
    portions: [yemekKasigi(25)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Humus',
    per_100g: { kalori: 167, protein_g: 7.5, yag_g: 9, karbonhidrat_g: 14, lif_g: 6 },
    portions: [yemekKasigi(25), porsiyon(100)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Patlıcan salatası',
    per_100g: { kalori: 102, protein_g: 1.6, yag_g: 8, karbonhidrat_g: 6, lif_g: 3 },
    portions: [yemekKasigi(25)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Mevsim yeşillik salata',
    per_100g: { kalori: 51, protein_g: 1.4, yag_g: 3.5, karbonhidrat_g: 3.5, lif_g: 1.8 },
    portions: [tabak(150)],
    source: 'bizim',
    verified: true,
  },

  // --- Tatlı ---
  {
    name_tr: 'Kazandibi',
    per_100g: { kalori: 172, protein_g: 4, yag_g: 4, karbonhidrat_g: 30, lif_g: 0.1 },
    portions: [porsiyon(120)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Revani',
    per_100g: { kalori: 289, protein_g: 4, yag_g: 9, karbonhidrat_g: 48, lif_g: 0.6 },
    portions: [dilim(90)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Künefe',
    per_100g: { kalori: 336, protein_g: 8, yag_g: 16, karbonhidrat_g: 40, lif_g: 0.8 },
    portions: [porsiyon(150)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Aşure',
    per_100g: { kalori: 162, protein_g: 3, yag_g: 2.5, karbonhidrat_g: 32, lif_g: 2.4 },
    portions: [kase(180)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Muhallebi',
    per_100g: { kalori: 129, protein_g: 3.4, yag_g: 3, karbonhidrat_g: 22, lif_g: 0.1 },
    portions: [kase(150)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Dondurma, sade',
    per_100g: { kalori: 200, protein_g: 3.6, yag_g: 10, karbonhidrat_g: 24, lif_g: 0.3 },
    portions: [porsiyon(100), kase(120)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Şekerpare',
    per_100g: { kalori: 306, protein_g: 4, yag_g: 10, karbonhidrat_g: 50, lif_g: 0.8 },
    portions: [adet(45)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'İrmik helvası',
    per_100g: { kalori: 333, protein_g: 4.5, yag_g: 15, karbonhidrat_g: 45, lif_g: 1 },
    portions: [porsiyon(120)],
    source: 'bizim',
    verified: true,
  },

  // --- İçecek ---
  {
    name_tr: 'Limonata',
    per_100g: { kalori: 41, protein_g: 0.2, yag_g: 0, karbonhidrat_g: 10, lif_g: 0.2 },
    portions: [bardak(200)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Şalgam suyu',
    per_100g: { kalori: 15, protein_g: 0.6, yag_g: 0.1, karbonhidrat_g: 3, lif_g: 0.6 },
    portions: [bardak(200)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Boza',
    per_100g: { kalori: 95, protein_g: 1.4, yag_g: 0.2, karbonhidrat_g: 22, lif_g: 1 },
    portions: [bardak(200)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Portakal suyu, taze',
    per_100g: { kalori: 46, protein_g: 0.7, yag_g: 0.2, karbonhidrat_g: 10.4, lif_g: 0.2 },
    portions: [bardak(200)],
    source: 'turkomp',
    verified: true,
  },

  // --- Ham gıda: protein ---
  {
    name_tr: 'Hindi göğsü, pişmiş',
    per_100g: { kalori: 134, protein_g: 29, yag_g: 2, karbonhidrat_g: 0, lif_g: 0 },
    portions: [porsiyon(150), avuc(100)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Çökelek',
    per_100g: { kalori: 105, protein_g: 17, yag_g: 3, karbonhidrat_g: 2.5, lif_g: 0 },
    portions: [yemekKasigi(25)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Kefir',
    per_100g: { kalori: 60, protein_g: 3.3, yag_g: 3.2, karbonhidrat_g: 4.5, lif_g: 0 },
    portions: [bardak(200)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Kinoa, pişmiş',
    per_100g: { kalori: 119, protein_g: 4.4, yag_g: 1.9, karbonhidrat_g: 21, lif_g: 2.8 },
    portions: [kase(180), kepce(120)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Karabuğday, pişmiş',
    per_100g: { kalori: 103, protein_g: 3.4, yag_g: 1, karbonhidrat_g: 20, lif_g: 2.7 },
    portions: [kase(180)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Yulaf kepeği',
    per_100g: { kalori: 331, protein_g: 17, yag_g: 7, karbonhidrat_g: 50, lif_g: 15 },
    portions: [yemekKasigi(10)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Chia tohumu',
    per_100g: { kalori: 515, protein_g: 17, yag_g: 31, karbonhidrat_g: 42, lif_g: 34 },
    portions: [yemekKasigi(12)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Keten tohumu',
    per_100g: { kalori: 566, protein_g: 18, yag_g: 42, karbonhidrat_g: 29, lif_g: 27 },
    portions: [yemekKasigi(10)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Tam buğday makarna, pişmiş',
    per_100g: { kalori: 135, protein_g: 5.3, yag_g: 1.1, karbonhidrat_g: 26, lif_g: 3.9 },
    portions: [kase(200)],
    source: 'turkomp',
    verified: true,
  },

  // --- Ham gıda: sebze ---
  {
    name_tr: 'Karnabahar, haşlanmış',
    per_100g: { kalori: 26, protein_g: 1.8, yag_g: 0.3, karbonhidrat_g: 4, lif_g: 2.3 },
    portions: [kase(150)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Kabak, haşlanmış',
    per_100g: { kalori: 19, protein_g: 1, yag_g: 0.3, karbonhidrat_g: 3, lif_g: 1 },
    portions: [kase(150)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Patlıcan, közlenmiş',
    per_100g: { kalori: 30, protein_g: 1, yag_g: 0.2, karbonhidrat_g: 6, lif_g: 3 },
    portions: [adet(120)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Kırmızı biber, çiğ',
    per_100g: { kalori: 31, protein_g: 1, yag_g: 0.3, karbonhidrat_g: 6, lif_g: 2.1 },
    portions: [adet(100)],
    source: 'turkomp',
    verified: true,
  },
  {
    /**
     * Yeşil biber katalogda HİÇ yoktu.
     *
     * Menemen, çoban salata, kısır — Türk mutfağının çekirdeğinde. Fotoğraf tanıma
     * "yeşil biber" dediğinde katalogda karşılığı olmadığı için **Pul biber**e
     * bağlanıyordu: bir avuç taze biber, bir tutam kuru acı biberin makrosuyla
     * yazılıyordu.
     */
    name_tr: 'Yeşil biber, çiğ',
    name_en: 'Green pepper, raw',
    per_100g: { kalori: 20, protein_g: 0.9, yag_g: 0.2, karbonhidrat_g: 4.6, lif_g: 1.7 },
    portions: [adet(35)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Havuç, çiğ',
    per_100g: { kalori: 44, protein_g: 0.9, yag_g: 0.2, karbonhidrat_g: 9.6, lif_g: 2.8 },
    portions: [adet(70)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Pancar, haşlanmış',
    per_100g: { kalori: 48, protein_g: 1.6, yag_g: 0.2, karbonhidrat_g: 10, lif_g: 2.8 },
    portions: [adet(80)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Beyaz lahana, çiğ',
    per_100g: { kalori: 29, protein_g: 1.3, yag_g: 0.1, karbonhidrat_g: 5.8, lif_g: 2.5 },
    portions: [kase(120)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Marul',
    per_100g: { kalori: 19, protein_g: 1.4, yag_g: 0.2, karbonhidrat_g: 2.9, lif_g: 1.3 },
    portions: [avuc(40)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Roka',
    per_100g: { kalori: 32, protein_g: 2.6, yag_g: 0.7, karbonhidrat_g: 3.7, lif_g: 1.6 },
    portions: [avuc(30)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Tere',
    per_100g: { kalori: 39, protein_g: 2.6, yag_g: 0.7, karbonhidrat_g: 5.5, lif_g: 1.1 },
    portions: [avuc(30)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Mantar, pişmiş',
    per_100g: { kalori: 33, protein_g: 3.1, yag_g: 0.5, karbonhidrat_g: 4, lif_g: 2.2 },
    portions: [kase(150)],
    source: 'turkomp',
    verified: true,
  },

  // --- Ham gıda: meyve ---
  {
    name_tr: 'Kavun',
    per_100g: { kalori: 38, protein_g: 0.8, yag_g: 0.2, karbonhidrat_g: 8.2, lif_g: 0.9 },
    portions: [dilim(180)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Kayısı',
    per_100g: { kalori: 53, protein_g: 1.4, yag_g: 0.4, karbonhidrat_g: 11, lif_g: 2 },
    portions: [adet(35)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Erik',
    per_100g: { kalori: 51, protein_g: 0.7, yag_g: 0.3, karbonhidrat_g: 11.4, lif_g: 1.4 },
    portions: [adet(60)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'İncir, taze',
    per_100g: { kalori: 82, protein_g: 0.8, yag_g: 0.3, karbonhidrat_g: 19, lif_g: 2.9 },
    portions: [adet(50)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Üzüm',
    per_100g: { kalori: 73, protein_g: 0.7, yag_g: 0.2, karbonhidrat_g: 17, lif_g: 0.9 },
    portions: [avuc(80)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Nar',
    per_100g: { kalori: 94, protein_g: 1.7, yag_g: 1.2, karbonhidrat_g: 19, lif_g: 4 },
    portions: [adet(200)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Mandalina',
    per_100g: { kalori: 59, protein_g: 0.8, yag_g: 0.3, karbonhidrat_g: 13.3, lif_g: 1.8 },
    portions: [adet(90)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Çilek',
    per_100g: { kalori: 36, protein_g: 0.7, yag_g: 0.3, karbonhidrat_g: 7.7, lif_g: 2 },
    portions: [kase(150), avuc(80)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Kivi',
    per_100g: { kalori: 68, protein_g: 1.1, yag_g: 0.5, karbonhidrat_g: 14.7, lif_g: 3 },
    portions: [adet(75)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Şeftali',
    per_100g: { kalori: 44, protein_g: 0.9, yag_g: 0.3, karbonhidrat_g: 9.5, lif_g: 1.5 },
    portions: [adet(150)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Armut',
    per_100g: { kalori: 63, protein_g: 0.4, yag_g: 0.1, karbonhidrat_g: 15.2, lif_g: 3.1 },
    portions: [adet(170)],
    source: 'turkomp',
    verified: true,
  },

  // --- Tariflerde geçen malzemeler ---
  {
    name_tr: 'Asma yaprağı, salamura',
    per_100g: { kalori: 59, protein_g: 4.3, yag_g: 2, karbonhidrat_g: 6, lif_g: 4 },
    portions: [adet(4), porsiyon(60)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Avokado',
    per_100g: { kalori: 177, protein_g: 2, yag_g: 15, karbonhidrat_g: 8.5, lif_g: 6.7 },
    portions: [adet(170), porsiyon(80)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Ayçiçek yağı',
    per_100g: { kalori: 900, protein_g: 0, yag_g: 100, karbonhidrat_g: 0, lif_g: 0 },
    portions: [yemekKasigi(12), cayKasigi(4)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Bezelye, haşlanmış',
    per_100g: { kalori: 88, protein_g: 5.4, yag_g: 0.4, karbonhidrat_g: 15.6, lif_g: 5.5 },
    portions: [kase(150), kepce(110)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Dereotu',
    per_100g: { kalori: 52, protein_g: 3.5, yag_g: 1.1, karbonhidrat_g: 7, lif_g: 2.1 },
    portions: [yemekKasigi(5)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Domates salçası',
    per_100g: { kalori: 97, protein_g: 4.3, yag_g: 0.5, karbonhidrat_g: 18.9, lif_g: 4.1 },
    portions: [yemekKasigi(18)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Fesleğen',
    per_100g: { kalori: 29, protein_g: 3.2, yag_g: 0.6, karbonhidrat_g: 2.6, lif_g: 1.6 },
    portions: [yemekKasigi(5)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Galeta unu',
    per_100g: { kalori: 389, protein_g: 13.4, yag_g: 5.3, karbonhidrat_g: 72, lif_g: 4.5 },
    portions: [yemekKasigi(10)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Yeşil mercimek, haşlanmış',
    per_100g: { kalori: 120, protein_g: 9, yag_g: 0.4, karbonhidrat_g: 20, lif_g: 8 },
    portions: [kepce(120), kase(200)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Hurma',
    per_100g: { kalori: 314, protein_g: 2.5, yag_g: 0.4, karbonhidrat_g: 75, lif_g: 8 },
    portions: [adet(8)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Kekik, kuru',
    per_100g: { kalori: 359, protein_g: 9, yag_g: 7.4, karbonhidrat_g: 64, lif_g: 37 },
    portions: [cayKasigi(1)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Kereviz kökü, haşlanmış',
    per_100g: { kalori: 31, protein_g: 1, yag_g: 0.3, karbonhidrat_g: 6, lif_g: 1.6 },
    portions: [kase(150)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Kimyon, toz',
    per_100g: { kalori: 449, protein_g: 17.8, yag_g: 22.3, karbonhidrat_g: 44.2, lif_g: 10.5 },
    portions: [cayKasigi(2)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Kuru kayısı',
    per_100g: { kalori: 270, protein_g: 3.4, yag_g: 0.5, karbonhidrat_g: 63, lif_g: 7.3 },
    portions: [adet(8), avuc(40)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Makarna, pişmiş',
    per_100g: { kalori: 155, protein_g: 5.8, yag_g: 0.9, karbonhidrat_g: 31, lif_g: 1.8 },
    portions: [kase(200), tabak(280)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Mantı, haşlanmış',
    per_100g: { kalori: 179, protein_g: 8, yag_g: 3, karbonhidrat_g: 30, lif_g: 1.4 },
    portions: [kase(200)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Maydanoz',
    per_100g: { kalori: 44, protein_g: 3, yag_g: 0.8, karbonhidrat_g: 6.3, lif_g: 3.3 },
    portions: [yemekKasigi(5), avuc(25)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Mısır, haşlanmış',
    per_100g: { kalori: 111, protein_g: 3.4, yag_g: 1.5, karbonhidrat_g: 21, lif_g: 2.4 },
    portions: [adet(90), kase(150)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Mısır unu',
    per_100g: { kalori: 370, protein_g: 6.9, yag_g: 3.9, karbonhidrat_g: 76.9, lif_g: 7.3 },
    portions: [yemekKasigi(10)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Nohut, çiğ',
    per_100g: { kalori: 380, protein_g: 20.5, yag_g: 6, karbonhidrat_g: 61, lif_g: 17 },
    portions: [bardak(180)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Pekmez',
    per_100g: { kalori: 285, protein_g: 1, yag_g: 0.1, karbonhidrat_g: 70, lif_g: 0 },
    portions: [yemekKasigi(20)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Sarımsak',
    per_100g: { kalori: 162, protein_g: 6.4, yag_g: 0.5, karbonhidrat_g: 33, lif_g: 2.1 },
    portions: [adet(4)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Tarhana, kuru',
    per_100g: { kalori: 332, protein_g: 12, yag_g: 4, karbonhidrat_g: 62, lif_g: 5 },
    portions: [yemekKasigi(12)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Tarçın, toz',
    per_100g: { kalori: 351, protein_g: 4, yag_g: 1.2, karbonhidrat_g: 81, lif_g: 53 },
    portions: [cayKasigi(2)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Taze fasulye, haşlanmış',
    per_100g: { kalori: 38, protein_g: 1.8, yag_g: 0.3, karbonhidrat_g: 7, lif_g: 3.2 },
    portions: [kepce(120), kase(200)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Buğday unu',
    per_100g: { kalori: 354, protein_g: 10.3, yag_g: 1, karbonhidrat_g: 76, lif_g: 2.7 },
    portions: [yemekKasigi(10), bardak(130)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Şehriye, çiğ',
    per_100g: { kalori: 358, protein_g: 12, yag_g: 1.5, karbonhidrat_g: 74, lif_g: 3 },
    portions: [yemekKasigi(12)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Limon suyu',
    per_100g: { kalori: 31, protein_g: 0.4, yag_g: 0.2, karbonhidrat_g: 6.9, lif_g: 0.3 },
    portions: [yemekKasigi(15)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Siyah zeytin',
    per_100g: { kalori: 163, protein_g: 1, yag_g: 15, karbonhidrat_g: 6, lif_g: 3.2 },
    portions: [adet(4), porsiyon(30)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Sucuk',
    per_100g: { kalori: 411, protein_g: 22, yag_g: 35, karbonhidrat_g: 2, lif_g: 0 },
    portions: [dilim(10), porsiyon(50)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Soğan',
    per_100g: { kalori: 42, protein_g: 1.1, yag_g: 0.1, karbonhidrat_g: 9.3, lif_g: 1.7 },
    portions: [adet(100)],
    source: 'turkomp',
    verified: true,
  },

  // --- Çiğ/pişmiş ayrımı: tarif hesabı için gerekli ---
  {
    name_tr: 'Hamsi, çiğ',
    per_100g: { kalori: 125, protein_g: 20.0, yag_g: 5.0, karbonhidrat_g: 0.0, lif_g: 0.0 },
    portions: [porsiyon(150)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Makarna, çiğ',
    per_100g: { kalori: 348, protein_g: 12.5, yag_g: 1.5, karbonhidrat_g: 71.0, lif_g: 3.0 },
    portions: [bardak(90)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Kuskus, çiğ',
    per_100g: { kalori: 345, protein_g: 12.8, yag_g: 0.6, karbonhidrat_g: 72.0, lif_g: 5.0 },
    portions: [bardak(120)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Pirinç, çiğ',
    per_100g: { kalori: 349, protein_g: 7.0, yag_g: 0.6, karbonhidrat_g: 79.0, lif_g: 1.3 },
    portions: [bardak(180), yemekKasigi(15)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Bulgur, çiğ',
    per_100g: { kalori: 365, protein_g: 12.3, yag_g: 1.3, karbonhidrat_g: 76.0, lif_g: 18.0 },
    portions: [bardak(150), yemekKasigi(12)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Mantı, çiğ',
    per_100g: { kalori: 296, protein_g: 11.0, yag_g: 3.5, karbonhidrat_g: 55.0, lif_g: 2.4 },
    portions: [bardak(100)],
    source: 'turkomp',
    verified: true,
  },

  // --- Bölgesel ana yemekler ---
  {
    name_tr: 'Ali Nazik',
    per_100g: { kalori: 184, protein_g: 12, yag_g: 12, karbonhidrat_g: 7, lif_g: 2.4 },
    portions: [porsiyon(280)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Beyti sarma',
    per_100g: { kalori: 263, protein_g: 14, yag_g: 15, karbonhidrat_g: 18, lif_g: 1.2 },
    portions: [porsiyon(250)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Çökertme kebabı',
    per_100g: { kalori: 242, protein_g: 13, yag_g: 14, karbonhidrat_g: 16, lif_g: 1.4 },
    portions: [porsiyon(300)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Kuzu tandır',
    per_100g: { kalori: 262, protein_g: 24, yag_g: 18, karbonhidrat_g: 1, lif_g: 0 },
    portions: [porsiyon(200)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Kuzu incik',
    per_100g: { kalori: 248, protein_g: 22, yag_g: 16, karbonhidrat_g: 4, lif_g: 0.8 },
    portions: [porsiyon(250)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Etli patlıcan kebabı',
    per_100g: { kalori: 201, protein_g: 13, yag_g: 13, karbonhidrat_g: 8, lif_g: 2.6 },
    portions: [porsiyon(280)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Kuru patlıcan dolması',
    per_100g: { kalori: 163, protein_g: 5, yag_g: 7, karbonhidrat_g: 20, lif_g: 3.4 },
    portions: [adet(60)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'İçli köfte',
    per_100g: { kalori: 244, protein_g: 8, yag_g: 12, karbonhidrat_g: 26, lif_g: 2.6 },
    portions: [adet(90)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Analı kızlı',
    per_100g: { kalori: 174, protein_g: 8, yag_g: 6, karbonhidrat_g: 22, lif_g: 3.6 },
    portions: [kase(250)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Keşkek',
    per_100g: { kalori: 195, protein_g: 11, yag_g: 7, karbonhidrat_g: 22, lif_g: 2 },
    portions: [porsiyon(250)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Perde pilav',
    per_100g: { kalori: 264, protein_g: 9, yag_g: 12, karbonhidrat_g: 30, lif_g: 1.6 },
    portions: [porsiyon(250)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Kabak dolma, zeytinyağlı',
    per_100g: { kalori: 130, protein_g: 3, yag_g: 6, karbonhidrat_g: 16, lif_g: 2.2 },
    portions: [adet(100)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Etli kabak dolma',
    per_100g: { kalori: 134, protein_g: 6, yag_g: 6.5, karbonhidrat_g: 13, lif_g: 1.8 },
    portions: [adet(110)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Karnabahar musakka',
    per_100g: { kalori: 115, protein_g: 5, yag_g: 7, karbonhidrat_g: 8, lif_g: 2.8 },
    portions: [porsiyon(250)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Ispanaklı yumurta',
    per_100g: { kalori: 147, protein_g: 8, yag_g: 11, karbonhidrat_g: 4, lif_g: 1.8 },
    portions: [porsiyon(200)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Fırında köfte patates',
    per_100g: { kalori: 220, protein_g: 14, yag_g: 12, karbonhidrat_g: 14, lif_g: 1.8 },
    portions: [porsiyon(300)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Tavuk güveç',
    per_100g: { kalori: 155, protein_g: 15, yag_g: 7, karbonhidrat_g: 8, lif_g: 1.6 },
    portions: [porsiyon(280)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Tavuk pilav, sokak usulü',
    per_100g: { kalori: 206, protein_g: 12, yag_g: 6, karbonhidrat_g: 26, lif_g: 0.8 },
    portions: [porsiyon(300)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Kuru köfte',
    per_100g: { kalori: 248, protein_g: 18, yag_g: 16, karbonhidrat_g: 8, lif_g: 0.6 },
    portions: [adet(40), porsiyon(180)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Terbiyeli köfte',
    per_100g: { kalori: 144, protein_g: 10, yag_g: 8, karbonhidrat_g: 8, lif_g: 0.8 },
    portions: [kase(250)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Etli lahana kapama',
    per_100g: { kalori: 122, protein_g: 7, yag_g: 6, karbonhidrat_g: 10, lif_g: 2.4 },
    portions: [porsiyon(280)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Şiş kebap',
    per_100g: { kalori: 231, protein_g: 22, yag_g: 15, karbonhidrat_g: 2, lif_g: 0.3 },
    portions: [porsiyon(180)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Kokoreç',
    per_100g: { kalori: 310, protein_g: 16, yag_g: 22, karbonhidrat_g: 12, lif_g: 0.6 },
    portions: [porsiyon(120)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Tavuk kanat, fırın',
    per_100g: { kalori: 253, protein_g: 24, yag_g: 17, karbonhidrat_g: 1, lif_g: 0 },
    portions: [adet(45), porsiyon(180)],
    source: 'bizim',
    verified: true,
  },

  // --- Deniz ve balık ---
  {
    name_tr: 'Çupra, ızgara',
    per_100g: { kalori: 138, protein_g: 21, yag_g: 6, karbonhidrat_g: 0, lif_g: 0 },
    portions: [porsiyon(200)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Palamut, fırın',
    per_100g: { kalori: 177, protein_g: 24, yag_g: 9, karbonhidrat_g: 0, lif_g: 0 },
    portions: [porsiyon(200)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'İstavrit tava',
    per_100g: { kalori: 221, protein_g: 19, yag_g: 13, karbonhidrat_g: 7, lif_g: 0.3 },
    portions: [porsiyon(180)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Kalamar tava',
    per_100g: { kalori: 220, protein_g: 16, yag_g: 12, karbonhidrat_g: 12, lif_g: 0.4 },
    portions: [porsiyon(150)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Balık ekmek',
    per_100g: { kalori: 232, protein_g: 14, yag_g: 8, karbonhidrat_g: 26, lif_g: 2 },
    portions: [adet(250)],
    source: 'bizim',
    verified: true,
  },

  // --- Zeytinyağlı ve sebze ---
  {
    name_tr: 'Zeytinyağlı barbunya',
    per_100g: { kalori: 126, protein_g: 5, yag_g: 5.5, karbonhidrat_g: 14, lif_g: 5 },
    portions: [kepce(120)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Zeytinyağlı ıspanak',
    per_100g: { kalori: 79, protein_g: 2.4, yag_g: 5, karbonhidrat_g: 6, lif_g: 2.6 },
    portions: [kepce(120)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Zeytinyağlı semizotu',
    per_100g: { kalori: 72, protein_g: 1.8, yag_g: 5, karbonhidrat_g: 5, lif_g: 2 },
    portions: [kepce(120)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Zeytinyağlı brokoli',
    per_100g: { kalori: 84, protein_g: 2.6, yag_g: 5.5, karbonhidrat_g: 6, lif_g: 3 },
    portions: [kase(200)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Zeytinyağlı kabak',
    per_100g: { kalori: 71, protein_g: 1.4, yag_g: 5, karbonhidrat_g: 5, lif_g: 1.4 },
    portions: [kepce(120)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Közlenmiş biber salatası',
    per_100g: { kalori: 96, protein_g: 1.2, yag_g: 7, karbonhidrat_g: 7, lif_g: 2.4 },
    portions: [yemekKasigi(25)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Fırında patlıcan, yoğurtlu',
    per_100g: { kalori: 111, protein_g: 3, yag_g: 7, karbonhidrat_g: 9, lif_g: 3.2 },
    portions: [porsiyon(250)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Mercimekli ıspanak',
    per_100g: { kalori: 104, protein_g: 5, yag_g: 4, karbonhidrat_g: 12, lif_g: 4 },
    portions: [kepce(130)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Turşu, karışık',
    per_100g: { kalori: 22, protein_g: 1, yag_g: 0.2, karbonhidrat_g: 4, lif_g: 1.6 },
    portions: [yemekKasigi(30)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Haşlanmış sebze tabağı',
    per_100g: { kalori: 49, protein_g: 2.4, yag_g: 0.4, karbonhidrat_g: 9, lif_g: 3.4 },
    portions: [tabak(250)],
    source: 'bizim',
    verified: true,
  },

  // --- Kahvaltı ve hamur ---
  {
    name_tr: 'Peynirli börek, fırın',
    per_100g: { kalori: 265, protein_g: 9, yag_g: 13, karbonhidrat_g: 28, lif_g: 1.2 },
    portions: [dilim(110)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Ispanaklı börek',
    per_100g: { kalori: 246, protein_g: 7.5, yag_g: 12, karbonhidrat_g: 27, lif_g: 1.8 },
    portions: [dilim(110)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Patatesli börek',
    per_100g: { kalori: 251, protein_g: 6, yag_g: 11, karbonhidrat_g: 32, lif_g: 1.8 },
    portions: [dilim(110)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Katmer',
    per_100g: { kalori: 368, protein_g: 7, yag_g: 20, karbonhidrat_g: 40, lif_g: 1.6 },
    portions: [porsiyon(120)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Bazlama',
    per_100g: { kalori: 268, protein_g: 8, yag_g: 4, karbonhidrat_g: 50, lif_g: 2.4 },
    portions: [adet(90)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Yufka ekmek',
    per_100g: { kalori: 274, protein_g: 9, yag_g: 2, karbonhidrat_g: 55, lif_g: 2.6 },
    portions: [adet(60)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Tam buğday ekmek',
    per_100g: { kalori: 235, protein_g: 9, yag_g: 3, karbonhidrat_g: 43, lif_g: 7 },
    portions: [dilim(30)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Beyaz ekmek',
    per_100g: { kalori: 244, protein_g: 8.5, yag_g: 1.5, karbonhidrat_g: 49, lif_g: 2.4 },
    portions: [dilim(25)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Peynirli pide',
    per_100g: { kalori: 266, protein_g: 12, yag_g: 10, karbonhidrat_g: 32, lif_g: 1.6 },
    portions: [dilim(90)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Kıymalı gözleme',
    per_100g: { kalori: 254, protein_g: 11, yag_g: 10, karbonhidrat_g: 30, lif_g: 1.8 },
    portions: [adet(160)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Ispanaklı gözleme',
    per_100g: { kalori: 220, protein_g: 7, yag_g: 8, karbonhidrat_g: 30, lif_g: 2.4 },
    portions: [adet(160)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Peynirli poğaça',
    per_100g: { kalori: 292, protein_g: 7.5, yag_g: 14, karbonhidrat_g: 34, lif_g: 1.4 },
    portions: [adet(80)],
    source: 'bizim',
    verified: true,
  },

  // --- Tatlı ve ara öğün ---
  {
    name_tr: 'Tulumba tatlısı',
    per_100g: { kalori: 376, protein_g: 3, yag_g: 16, karbonhidrat_g: 55, lif_g: 0.6 },
    portions: [adet(30)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Lokma',
    per_100g: { kalori: 350, protein_g: 4, yag_g: 14, karbonhidrat_g: 52, lif_g: 1 },
    portions: [adet(20)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Kadayıf',
    per_100g: { kalori: 362, protein_g: 6, yag_g: 18, karbonhidrat_g: 44, lif_g: 1.2 },
    portions: [porsiyon(120)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Fırın sütlaç',
    per_100g: { kalori: 162, protein_g: 4.5, yag_g: 3.5, karbonhidrat_g: 28, lif_g: 0.2 },
    portions: [porsiyon(150)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Ayva tatlısı',
    per_100g: { kalori: 141, protein_g: 0.6, yag_g: 0.3, karbonhidrat_g: 34, lif_g: 3.6 },
    portions: [porsiyon(150)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Kabak tatlısı',
    per_100g: { kalori: 133, protein_g: 0.8, yag_g: 0.2, karbonhidrat_g: 32, lif_g: 2 },
    portions: [porsiyon(150)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Cevizli sucuk',
    per_100g: { kalori: 406, protein_g: 6, yag_g: 18, karbonhidrat_g: 55, lif_g: 2.4 },
    portions: [dilim(30)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Lokum',
    per_100g: { kalori: 314, protein_g: 0.2, yag_g: 0.1, karbonhidrat_g: 78, lif_g: 0.4 },
    portions: [adet(12)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Tahin helvası',
    per_100g: { kalori: 528, protein_g: 12, yag_g: 32, karbonhidrat_g: 48, lif_g: 4 },
    portions: [dilim(40)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Meyveli yoğurt',
    per_100g: { kalori: 94, protein_g: 4, yag_g: 2.5, karbonhidrat_g: 14, lif_g: 0.6 },
    portions: [kase(150)],
    source: 'bizim',
    verified: true,
  },

  // --- İçecek ve süt ürünü ---
  {
    name_tr: 'Süt, tam yağlı',
    per_100g: { kalori: 64, protein_g: 3.2, yag_g: 3.6, karbonhidrat_g: 4.7, lif_g: 0 },
    portions: [bardak(200)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Süt, yağsız',
    per_100g: { kalori: 35, protein_g: 3.4, yag_g: 0.2, karbonhidrat_g: 4.9, lif_g: 0 },
    portions: [bardak(200)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Yoğurt, tam yağlı',
    per_100g: { kalori: 64, protein_g: 3.4, yag_g: 3.5, karbonhidrat_g: 4.7, lif_g: 0 },
    portions: [kase(200)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Yoğurt, yağsız',
    per_100g: { kalori: 38, protein_g: 4, yag_g: 0.2, karbonhidrat_g: 5, lif_g: 0 },
    portions: [kase(200)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Beyaz peynir, tam yağlı',
    per_100g: { kalori: 274, protein_g: 17, yag_g: 22, karbonhidrat_g: 2, lif_g: 0 },
    portions: [dilim(30)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Tulum peyniri',
    per_100g: { kalori: 374, protein_g: 24, yag_g: 30, karbonhidrat_g: 2, lif_g: 0 },
    portions: [dilim(25)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Krem peynir',
    per_100g: { kalori: 310, protein_g: 6, yag_g: 30, karbonhidrat_g: 4, lif_g: 0 },
    portions: [yemekKasigi(20)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Sade soda',
    per_100g: { kalori: 0, protein_g: 0, yag_g: 0, karbonhidrat_g: 0, lif_g: 0 },
    portions: [adet(200)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Bitki çayı',
    per_100g: { kalori: 1, protein_g: 0, yag_g: 0, karbonhidrat_g: 0.2, lif_g: 0 },
    portions: [bardak(200)],
    source: 'turkomp',
    verified: true,
  },

  // --- Kuruyemiş ve tohum ---
  {
    name_tr: 'Antep fıstığı',
    per_100g: { kalori: 597, protein_g: 20, yag_g: 45, karbonhidrat_g: 28, lif_g: 10 },
    portions: [avuc(30)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Kaju',
    per_100g: { kalori: 588, protein_g: 18, yag_g: 44, karbonhidrat_g: 30, lif_g: 3.3 },
    portions: [avuc(30)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Ay çekirdeği',
    per_100g: { kalori: 623, protein_g: 21, yag_g: 51, karbonhidrat_g: 20, lif_g: 8.6 },
    portions: [avuc(30)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Kabak çekirdeği',
    per_100g: { kalori: 605, protein_g: 30, yag_g: 49, karbonhidrat_g: 11, lif_g: 6 },
    portions: [avuc(30)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Yer fıstığı',
    per_100g: { kalori: 609, protein_g: 26, yag_g: 49, karbonhidrat_g: 16, lif_g: 8.5 },
    portions: [avuc(30)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Fıstık ezmesi',
    per_100g: { kalori: 630, protein_g: 25, yag_g: 50, karbonhidrat_g: 20, lif_g: 6 },
    portions: [yemekKasigi(20)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Kuru üzüm',
    per_100g: { kalori: 333, protein_g: 3.1, yag_g: 0.5, karbonhidrat_g: 79, lif_g: 3.7 },
    portions: [avuc(30)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Kuru incir',
    per_100g: { kalori: 277, protein_g: 3.3, yag_g: 0.9, karbonhidrat_g: 64, lif_g: 9.8 },
    portions: [adet(20)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Ceviz, kabuklu içi',
    per_100g: { kalori: 701, protein_g: 15, yag_g: 65, karbonhidrat_g: 14, lif_g: 6.7 },
    portions: [adet(5)],
    source: 'turkomp',
    verified: true,
  },

  // --- Tarif malzemesi tamamlayıcıları ---
  {
    name_tr: 'Semizotu',
    per_100g: { kalori: 25, protein_g: 2.0, yag_g: 0.4, karbonhidrat_g: 3.4, lif_g: 1.0 },
    portions: [kase(150), avuc(50)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Pırasa',
    per_100g: { kalori: 65, protein_g: 1.5, yag_g: 0.3, karbonhidrat_g: 14.0, lif_g: 1.8 },
    portions: [adet(150), kepce(110)],
    source: 'turkomp',
    verified: true,
  },

  // --- Çiğ karşılıklar: tarif hesabı için ---
  {
    name_tr: 'Dana kuşbaşı, çiğ',
    per_100g: { kalori: 188, protein_g: 20.0, yag_g: 12.0, karbonhidrat_g: 0.0, lif_g: 0.0 },
    portions: [porsiyon(150)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Yeşil mercimek, çiğ',
    per_100g: { kalori: 350, protein_g: 25.0, yag_g: 1.1, karbonhidrat_g: 60.0, lif_g: 30.0 },
    portions: [bardak(190), yemekKasigi(14)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Kuru fasulye, çiğ',
    per_100g: { kalori: 338, protein_g: 21.0, yag_g: 1.5, karbonhidrat_g: 60.0, lif_g: 25.0 },
    portions: [bardak(180)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Nohut, haşlanmış',
    per_100g: { kalori: 167, protein_g: 8.9, yag_g: 2.6, karbonhidrat_g: 27.0, lif_g: 7.6 },
    portions: [kepce(120), kase(200)],
    source: 'turkomp',
    verified: true,
  },

  // --- Bölgesel yemekler ---
  {
    name_tr: 'Mercimekli köfte',
    per_100g: { kalori: 189, protein_g: 6, yag_g: 5, karbonhidrat_g: 30, lif_g: 5 },
    portions: [adet(30), porsiyon(150)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Ekşili köfte',
    per_100g: { kalori: 139, protein_g: 9, yag_g: 7, karbonhidrat_g: 10, lif_g: 1.2 },
    portions: [kase(250)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Yuvalama',
    per_100g: { kalori: 158, protein_g: 8, yag_g: 6, karbonhidrat_g: 18, lif_g: 1.6 },
    portions: [kase(250)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Arabaşı çorbası',
    per_100g: { kalori: 117, protein_g: 6, yag_g: 5, karbonhidrat_g: 12, lif_g: 0.6 },
    portions: [kase(250)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Bamya yemeği',
    per_100g: { kalori: 82, protein_g: 2.4, yag_g: 4.5, karbonhidrat_g: 8, lif_g: 3.2 },
    portions: [kepce(120)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Türlü kebap',
    per_100g: { kalori: 192, protein_g: 11, yag_g: 12, karbonhidrat_g: 10, lif_g: 2.4 },
    portions: [porsiyon(280)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Sac kavurma',
    per_100g: { kalori: 218, protein_g: 18, yag_g: 14, karbonhidrat_g: 5, lif_g: 1 },
    portions: [porsiyon(200)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Kuzu pirzola',
    per_100g: { kalori: 268, protein_g: 22, yag_g: 20, karbonhidrat_g: 0, lif_g: 0 },
    portions: [adet(60), porsiyon(180)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Dana bonfile',
    per_100g: { kalori: 185, protein_g: 26, yag_g: 9, karbonhidrat_g: 0, lif_g: 0 },
    portions: [porsiyon(180)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Ciğer tava',
    per_100g: { kalori: 220, protein_g: 22, yag_g: 12, karbonhidrat_g: 6, lif_g: 0.2 },
    portions: [porsiyon(150)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Arnavut ciğeri',
    per_100g: { kalori: 242, protein_g: 21, yag_g: 14, karbonhidrat_g: 8, lif_g: 0.6 },
    portions: [porsiyon(150)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Etli ekmek',
    per_100g: { kalori: 245, protein_g: 11, yag_g: 9, karbonhidrat_g: 30, lif_g: 1.8 },
    portions: [dilim(90), porsiyon(300)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Su böreği, kıymalı',
    per_100g: { kalori: 252, protein_g: 10, yag_g: 12, karbonhidrat_g: 26, lif_g: 1.2 },
    portions: [dilim(120)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Mercimekli erişte',
    per_100g: { kalori: 193, protein_g: 7, yag_g: 5, karbonhidrat_g: 30, lif_g: 3 },
    portions: [kase(220)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Tarhana keşkeği',
    per_100g: { kalori: 186, protein_g: 9, yag_g: 6, karbonhidrat_g: 24, lif_g: 2 },
    portions: [kase(250)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Kelle paça çorbası',
    per_100g: { kalori: 90, protein_g: 7, yag_g: 6, karbonhidrat_g: 2, lif_g: 0 },
    portions: [kase(250)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Mercimekli bulgur pilavı',
    per_100g: { kalori: 191, protein_g: 6.5, yag_g: 5, karbonhidrat_g: 30, lif_g: 6 },
    portions: [kepce(120)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Firik pilavı',
    per_100g: { kalori: 181, protein_g: 6, yag_g: 5, karbonhidrat_g: 28, lif_g: 5 },
    portions: [kepce(120)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Zeytinyağlı kereviz salatası',
    per_100g: { kalori: 87, protein_g: 1.2, yag_g: 6, karbonhidrat_g: 7, lif_g: 2 },
    portions: [kase(180)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Şakşuka',
    per_100g: { kalori: 133, protein_g: 1.8, yag_g: 10, karbonhidrat_g: 9, lif_g: 3.2 },
    portions: [yemekKasigi(30), porsiyon(150)],
    source: 'bizim',
    verified: true,
  },

  // --- Market ürünleri ---
  {
    name_tr: 'Kepekli bisküvi',
    per_100g: { kalori: 430, protein_g: 8, yag_g: 14, karbonhidrat_g: 68, lif_g: 6 },
    portions: [adet(10), porsiyon(30)],
    source: 'openfoodfacts',
    verified: true,
  },
  {
    name_tr: 'Yulaflı bar',
    per_100g: { kalori: 398, protein_g: 8, yag_g: 14, karbonhidrat_g: 60, lif_g: 7 },
    portions: [adet(40)],
    source: 'openfoodfacts',
    verified: true,
  },
  {
    name_tr: 'Protein bar',
    per_100g: { kalori: 388, protein_g: 30, yag_g: 12, karbonhidrat_g: 40, lif_g: 6 },
    portions: [adet(60)],
    source: 'openfoodfacts',
    verified: true,
  },
  {
    name_tr: 'Kepekli kraker',
    per_100g: { kalori: 416, protein_g: 9, yag_g: 12, karbonhidrat_g: 68, lif_g: 6 },
    portions: [porsiyon(30)],
    source: 'openfoodfacts',
    verified: true,
  },
  {
    name_tr: 'Bitter çikolata, %70',
    per_100g: { kalori: 594, protein_g: 8, yag_g: 42, karbonhidrat_g: 46, lif_g: 11 },
    portions: [dilim(10), porsiyon(30)],
    source: 'openfoodfacts',
    verified: true,
  },
  {
    name_tr: 'Sütlü çikolata',
    per_100g: { kalori: 550, protein_g: 7.5, yag_g: 32, karbonhidrat_g: 58, lif_g: 2.4 },
    portions: [dilim(10), porsiyon(30)],
    source: 'openfoodfacts',
    verified: true,
  },
  {
    name_tr: 'Mısır gevreği, şekersiz',
    per_100g: { kalori: 370, protein_g: 8, yag_g: 2, karbonhidrat_g: 80, lif_g: 8 },
    portions: [kase(40)],
    source: 'openfoodfacts',
    verified: true,
  },
  {
    name_tr: 'Granola',
    per_100g: { kalori: 442, protein_g: 10, yag_g: 18, karbonhidrat_g: 60, lif_g: 8 },
    portions: [kase(50)],
    source: 'openfoodfacts',
    verified: true,
  },
  {
    name_tr: 'Kepekli ekmek',
    per_100g: { kalori: 246, protein_g: 9.5, yag_g: 3.5, karbonhidrat_g: 44, lif_g: 6 },
    portions: [dilim(30)],
    source: 'openfoodfacts',
    verified: true,
  },
  {
    name_tr: 'Çavdar ekmeği',
    per_100g: { kalori: 243, protein_g: 9, yag_g: 3, karbonhidrat_g: 45, lif_g: 8 },
    portions: [dilim(30)],
    source: 'openfoodfacts',
    verified: true,
  },
  {
    name_tr: 'Ayçöreği',
    per_100g: { kalori: 412, protein_g: 8, yag_g: 20, karbonhidrat_g: 50, lif_g: 2 },
    portions: [adet(70)],
    source: 'openfoodfacts',
    verified: true,
  },
  {
    name_tr: 'Labne peyniri',
    per_100g: { kalori: 260, protein_g: 7, yag_g: 24, karbonhidrat_g: 4, lif_g: 0 },
    portions: [yemekKasigi(20)],
    source: 'openfoodfacts',
    verified: true,
  },
  {
    name_tr: 'Hindi füme',
    per_100g: { kalori: 128, protein_g: 22, yag_g: 4, karbonhidrat_g: 1, lif_g: 0 },
    portions: [dilim(20)],
    source: 'openfoodfacts',
    verified: true,
  },
  {
    name_tr: 'Ton balığı, yağda',
    per_100g: { kalori: 168, protein_g: 24, yag_g: 8, karbonhidrat_g: 0, lif_g: 0 },
    portions: [porsiyon(80)],
    source: 'openfoodfacts',
    verified: true,
  },
  {
    name_tr: 'Zeytinyağlı sardalya',
    per_100g: { kalori: 192, protein_g: 21, yag_g: 12, karbonhidrat_g: 0, lif_g: 0 },
    portions: [porsiyon(90)],
    source: 'openfoodfacts',
    verified: true,
  },
  {
    name_tr: 'Yoğurtlu içecek, sade',
    per_100g: { kalori: 46, protein_g: 3.2, yag_g: 1.5, karbonhidrat_g: 5, lif_g: 0 },
    portions: [adet(250)],
    source: 'openfoodfacts',
    verified: true,
  },
  {
    name_tr: 'Badem sütü, şekersiz',
    per_100g: { kalori: 16, protein_g: 0.6, yag_g: 1.2, karbonhidrat_g: 0.6, lif_g: 0.4 },
    portions: [bardak(200)],
    source: 'openfoodfacts',
    verified: true,
  },
  {
    name_tr: 'Soya sütü, şekersiz',
    per_100g: { kalori: 37, protein_g: 3.3, yag_g: 1.8, karbonhidrat_g: 1.8, lif_g: 0.6 },
    portions: [bardak(200)],
    source: 'openfoodfacts',
    verified: true,
  },
  {
    name_tr: 'Yulaf sütü',
    per_100g: { kalori: 46, protein_g: 1, yag_g: 1.5, karbonhidrat_g: 7, lif_g: 0.8 },
    portions: [bardak(200)],
    source: 'openfoodfacts',
    verified: true,
  },
  {
    name_tr: 'Peynir altı suyu tozu',
    per_100g: { kalori: 406, protein_g: 80, yag_g: 6, karbonhidrat_g: 8, lif_g: 0 },
    portions: [{ id: 'olcek', ad: '1 ölçek', gram: 30 }],
    source: 'openfoodfacts',
    verified: true,
  },

  // --- Zincir ve dışarıda yemek ---
  {
    name_tr: 'Tavuklu wrap, zincir',
    per_100g: { kalori: 216, protein_g: 14, yag_g: 8, karbonhidrat_g: 22, lif_g: 2 },
    portions: [adet(250)],
    source: 'zincir',
    verified: true,
  },
  {
    name_tr: 'Hamburger, klasik',
    per_100g: { kalori: 269, protein_g: 14, yag_g: 13, karbonhidrat_g: 24, lif_g: 1.4 },
    portions: [adet(220)],
    source: 'zincir',
    verified: true,
  },
  {
    name_tr: 'Patates kızartması, orta',
    per_100g: { kalori: 293, protein_g: 3.4, yag_g: 15, karbonhidrat_g: 36, lif_g: 3.4 },
    portions: [porsiyon(120)],
    source: 'zincir',
    verified: true,
  },
  {
    name_tr: 'Pizza, margarita',
    per_100g: { kalori: 254, protein_g: 11, yag_g: 10, karbonhidrat_g: 30, lif_g: 2 },
    portions: [dilim(110)],
    source: 'zincir',
    verified: true,
  },
  {
    name_tr: 'Sushi, somonlu',
    per_100g: { kalori: 188, protein_g: 8, yag_g: 4, karbonhidrat_g: 30, lif_g: 1 },
    portions: [adet(30), porsiyon(240)],
    source: 'zincir',
    verified: true,
  },
  {
    name_tr: 'Kumpir, orta',
    per_100g: { kalori: 240, protein_g: 5, yag_g: 12, karbonhidrat_g: 28, lif_g: 3 },
    portions: [adet(350)],
    source: 'zincir',
    verified: true,
  },
  {
    name_tr: 'Tost, karışık',
    per_100g: { kalori: 303, protein_g: 14, yag_g: 15, karbonhidrat_g: 28, lif_g: 1.6 },
    portions: [adet(160)],
    source: 'zincir',
    verified: true,
  },
  {
    name_tr: 'Çiğ köfte dürüm',
    per_100g: { kalori: 230, protein_g: 6, yag_g: 6, karbonhidrat_g: 38, lif_g: 5 },
    portions: [adet(200)],
    source: 'zincir',
    verified: true,
  },
  {
    name_tr: 'Kokoreç ekmek',
    per_100g: { kalori: 322, protein_g: 14, yag_g: 18, karbonhidrat_g: 26, lif_g: 1.4 },
    portions: [adet(200)],
    source: 'zincir',
    verified: true,
  },
  {
    name_tr: 'Islak hamburger',
    per_100g: { kalori: 308, protein_g: 13, yag_g: 16, karbonhidrat_g: 28, lif_g: 1.4 },
    portions: [adet(150)],
    source: 'zincir',
    verified: true,
  },

  // --- Baharat ve sos ---
  {
    name_tr: 'Nar ekşisi',
    per_100g: { kalori: 243, protein_g: 0.6, yag_g: 0.1, karbonhidrat_g: 60, lif_g: 0.6 },
    portions: [yemekKasigi(18)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Sirke',
    per_100g: { kalori: 4, protein_g: 0, yag_g: 0, karbonhidrat_g: 0.9, lif_g: 0 },
    portions: [yemekKasigi(15)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Ketçap',
    per_100g: { kalori: 111, protein_g: 1.2, yag_g: 0.2, karbonhidrat_g: 26, lif_g: 0.4 },
    portions: [yemekKasigi(17)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Mayonez',
    per_100g: { kalori: 687, protein_g: 1, yag_g: 75, karbonhidrat_g: 2, lif_g: 0 },
    portions: [yemekKasigi(14)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Hardal',
    per_100g: { kalori: 78, protein_g: 4.4, yag_g: 4, karbonhidrat_g: 6, lif_g: 3.3 },
    portions: [cayKasigi(5)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Pul biber',
    per_100g: { kalori: 374, protein_g: 12, yag_g: 14, karbonhidrat_g: 50, lif_g: 27 },
    portions: [cayKasigi(2)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Karabiber',
    per_100g: { kalori: 327, protein_g: 10.4, yag_g: 3.3, karbonhidrat_g: 64, lif_g: 25 },
    portions: [cayKasigi(2)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Nane, kuru',
    per_100g: { kalori: 342, protein_g: 20, yag_g: 6, karbonhidrat_g: 52, lif_g: 30 },
    portions: [cayKasigi(1)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Sumak',
    per_100g: { kalori: 319, protein_g: 4, yag_g: 7, karbonhidrat_g: 60, lif_g: 30 },
    portions: [cayKasigi(2)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Tuz',
    per_100g: { kalori: 0, protein_g: 0, yag_g: 0, karbonhidrat_g: 0, lif_g: 0 },
    portions: [cayKasigi(5)],
    source: 'turkomp',
    verified: true,
  },

  // --- Meyve — kuyruk ---
  {
    name_tr: 'Kiraz',
    per_100g: { kalori: 71, protein_g: 1.1, yag_g: 0.3, karbonhidrat_g: 16, lif_g: 2.1 },
    portions: [kase(150), porsiyon(100)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Vişne',
    per_100g: { kalori: 56, protein_g: 1, yag_g: 0.3, karbonhidrat_g: 12.2, lif_g: 1.6 },
    portions: [kase(150)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Ananas',
    per_100g: { kalori: 55, protein_g: 0.5, yag_g: 0.1, karbonhidrat_g: 13.1, lif_g: 1.4 },
    portions: [dilim(80), kase(150)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Greyfurt',
    per_100g: { kalori: 47, protein_g: 0.8, yag_g: 0.1, karbonhidrat_g: 10.7, lif_g: 1.6 },
    portions: [adet(250), porsiyon(150)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Böğürtlen',
    per_100g: { kalori: 48, protein_g: 1.4, yag_g: 0.5, karbonhidrat_g: 9.6, lif_g: 5.3 },
    portions: [kase(120)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Ahududu',
    per_100g: { kalori: 59, protein_g: 1.2, yag_g: 0.7, karbonhidrat_g: 11.9, lif_g: 6.5 },
    portions: [kase(120)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Yaban mersini',
    per_100g: { kalori: 64, protein_g: 0.7, yag_g: 0.3, karbonhidrat_g: 14.5, lif_g: 2.4 },
    portions: [kase(120)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Kiraz, kuru',
    per_100g: { kalori: 322, protein_g: 3, yag_g: 2, karbonhidrat_g: 73, lif_g: 6 },
    portions: [porsiyon(40)],
    source: 'turkomp',
    verified: true,
  },

  // --- Sebze — kuyruk ---
  {
    name_tr: 'Turp, çiğ',
    per_100g: { kalori: 17, protein_g: 0.7, yag_g: 0.1, karbonhidrat_g: 3.4, lif_g: 1.6 },
    portions: [adet(20), kase(100)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Kırmızı turp',
    per_100g: { kalori: 17, protein_g: 0.7, yag_g: 0.1, karbonhidrat_g: 3.4, lif_g: 1.6 },
    portions: [adet(15)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Enginar, haşlanmış',
    per_100g: { kalori: 58, protein_g: 2.9, yag_g: 0.3, karbonhidrat_g: 11, lif_g: 5.4 },
    portions: [adet(120)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Bakla, haşlanmış',
    per_100g: { kalori: 86, protein_g: 7.6, yag_g: 0.5, karbonhidrat_g: 12.9, lif_g: 5.4 },
    portions: [kase(180)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Kuşkonmaz, haşlanmış',
    per_100g: { kalori: 28, protein_g: 2.4, yag_g: 0.2, karbonhidrat_g: 4.1, lif_g: 2 },
    portions: [porsiyon(100)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Tatlı patates, fırında',
    per_100g: { kalori: 92, protein_g: 2, yag_g: 0.1, karbonhidrat_g: 20.7, lif_g: 3.3 },
    portions: [adet(150)],
    source: 'turkomp',
    verified: true,
  },

  // --- Balık — kuyruk ---
  {
    name_tr: 'Uskumru, ızgara',
    per_100g: { kalori: 236, protein_g: 23, yag_g: 16, karbonhidrat_g: 0, lif_g: 0 },
    portions: [porsiyon(180)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Alabalık, ızgara',
    per_100g: { kalori: 151, protein_g: 22, yag_g: 7, karbonhidrat_g: 0, lif_g: 0 },
    portions: [porsiyon(200)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Lüfer, ızgara',
    per_100g: { kalori: 142, protein_g: 22, yag_g: 6, karbonhidrat_g: 0, lif_g: 0 },
    portions: [porsiyon(180)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Mezgit, fırın',
    per_100g: { kalori: 98, protein_g: 20, yag_g: 2, karbonhidrat_g: 0, lif_g: 0 },
    portions: [porsiyon(180)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Somon, çiğ',
    per_100g: { kalori: 197, protein_g: 20, yag_g: 13, karbonhidrat_g: 0, lif_g: 0 },
    portions: [porsiyon(150)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Midye, haşlanmış',
    per_100g: { kalori: 119, protein_g: 17, yag_g: 3, karbonhidrat_g: 6, lif_g: 0 },
    portions: [adet(15), porsiyon(100)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Kalamar, haşlanmış',
    per_100g: { kalori: 90, protein_g: 16, yag_g: 1.5, karbonhidrat_g: 3, lif_g: 0 },
    portions: [porsiyon(120)],
    source: 'turkomp',
    verified: true,
  },

  // --- Şarküteri — kuyruk ---
  {
    name_tr: 'Pastırma',
    per_100g: { kalori: 236, protein_g: 30, yag_g: 12, karbonhidrat_g: 2, lif_g: 0 },
    portions: [dilim(8), porsiyon(40)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Salam, dana',
    per_100g: { kalori: 260, protein_g: 17, yag_g: 20, karbonhidrat_g: 3, lif_g: 0 },
    portions: [dilim(15), porsiyon(50)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Sosis, dana',
    per_100g: { kalori: 284, protein_g: 13, yag_g: 24, karbonhidrat_g: 4, lif_g: 0 },
    portions: [adet(40), porsiyon(80)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Jambon, hindi',
    per_100g: { kalori: 124, protein_g: 20, yag_g: 4, karbonhidrat_g: 2, lif_g: 0 },
    portions: [dilim(15)],
    source: 'turkomp',
    verified: true,
  },

  // --- Tahıl — kuyruk ---
  {
    name_tr: 'Arpa, pişmiş',
    per_100g: { kalori: 126, protein_g: 2.3, yag_g: 0.4, karbonhidrat_g: 28.2, lif_g: 3.8 },
    portions: [kepce(120)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Arpa, çiğ',
    per_100g: { kalori: 365, protein_g: 12.5, yag_g: 2.3, karbonhidrat_g: 73.5, lif_g: 17.3 },
    portions: [bardak(180)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Yulaf, pişmiş',
    per_100g: { kalori: 70, protein_g: 2.4, yag_g: 1.4, karbonhidrat_g: 12, lif_g: 1.7 },
    portions: [kase(220)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Pirinç, esmer, pişmiş',
    per_100g: { kalori: 110, protein_g: 2.6, yag_g: 0.9, karbonhidrat_g: 23, lif_g: 1.8 },
    portions: [kepce(120)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Makarna, tam buğday, çiğ',
    per_100g: { kalori: 358, protein_g: 13, yag_g: 2.5, karbonhidrat_g: 71, lif_g: 8 },
    portions: [porsiyon(80)],
    source: 'turkomp',
    verified: true,
  },

  // --- Kuruyemiş — kuyruk ---
  {
    name_tr: 'Susam',
    per_100g: { kalori: 612, protein_g: 17.7, yag_g: 49.7, karbonhidrat_g: 23.4, lif_g: 11.8 },
    portions: [yemekKasigi(9)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Kuru üzüm, sarı',
    per_100g: { kalori: 334, protein_g: 3.1, yag_g: 0.5, karbonhidrat_g: 79.2, lif_g: 3.7 },
    portions: [yemekKasigi(15), porsiyon(40)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Leblebi',
    per_100g: { kalori: 362, protein_g: 19, yag_g: 6, karbonhidrat_g: 58, lif_g: 12 },
    portions: [avuc(30)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Kestane, haşlanmış',
    per_100g: { kalori: 133, protein_g: 2, yag_g: 1.4, karbonhidrat_g: 28, lif_g: 5 },
    portions: [adet(15), porsiyon(100)],
    source: 'turkomp',
    verified: true,
  },

  // --- Yemek — kuyruk ---
  {
    name_tr: 'Kısır',
    per_100g: { kalori: 218, protein_g: 4.5, yag_g: 8, karbonhidrat_g: 32, lif_g: 5 },
    portions: [kase(180), porsiyon(150)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Piyaz',
    per_100g: { kalori: 187, protein_g: 6.5, yag_g: 9, karbonhidrat_g: 20, lif_g: 6 },
    portions: [porsiyon(200)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Fasulye piyazı',
    per_100g: { kalori: 187, protein_g: 6.5, yag_g: 9, karbonhidrat_g: 20, lif_g: 6 },
    portions: [porsiyon(200)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Mercimek salatası',
    per_100g: { kalori: 150, protein_g: 6, yag_g: 6, karbonhidrat_g: 18, lif_g: 5.5 },
    portions: [kase(180)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Yoğurtlu semizotu',
    per_100g: { kalori: 57, protein_g: 2.5, yag_g: 3, karbonhidrat_g: 5, lif_g: 1.2 },
    portions: [kase(180)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Zeytinyağlı bamya',
    per_100g: { kalori: 89, protein_g: 1.8, yag_g: 6, karbonhidrat_g: 7, lif_g: 3 },
    portions: [kepce(120)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Karnabahar kızartma',
    per_100g: { kalori: 134, protein_g: 2, yag_g: 10, karbonhidrat_g: 9, lif_g: 2.4 },
    portions: [porsiyon(150)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Sebzeli kuskus',
    per_100g: { kalori: 165, protein_g: 4, yag_g: 5, karbonhidrat_g: 26, lif_g: 2.6 },
    portions: [kase(200)],
    source: 'bizim',
    verified: true,
  },

  // --- İçecek — kuyruk ---
  {
    name_tr: 'Meyve suyu, portakal',
    per_100g: { kalori: 46, protein_g: 0.7, yag_g: 0.2, karbonhidrat_g: 10.4, lif_g: 0.2 },
    portions: [bardak(200)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Meyve suyu, vişne',
    per_100g: { kalori: 50, protein_g: 0.4, yag_g: 0.1, karbonhidrat_g: 12, lif_g: 0.1 },
    portions: [bardak(200)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Meyve suyu, şeftali',
    per_100g: { kalori: 52, protein_g: 0.4, yag_g: 0.1, karbonhidrat_g: 12.5, lif_g: 0.2 },
    portions: [bardak(200)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Bira',
    per_100g: { kalori: 16, protein_g: 0.5, yag_g: 0, karbonhidrat_g: 3.6, lif_g: 0 },
    portions: [bardak(330)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Şarap, kırmızı',
    per_100g: { kalori: 11, protein_g: 0.1, yag_g: 0, karbonhidrat_g: 2.6, lif_g: 0 },
    portions: [bardak(150)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Şarap, beyaz',
    per_100g: { kalori: 11, protein_g: 0.1, yag_g: 0, karbonhidrat_g: 2.6, lif_g: 0 },
    portions: [bardak(150)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Rakı',
    per_100g: { kalori: 0, protein_g: 0, yag_g: 0, karbonhidrat_g: 0, lif_g: 0 },
    portions: [bardak(50)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Votka',
    per_100g: { kalori: 0, protein_g: 0, yag_g: 0, karbonhidrat_g: 0, lif_g: 0 },
    portions: [bardak(50)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Viski',
    per_100g: { kalori: 0, protein_g: 0, yag_g: 0, karbonhidrat_g: 0.1, lif_g: 0 },
    portions: [bardak(50)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Kola',
    per_100g: { kalori: 42, protein_g: 0, yag_g: 0, karbonhidrat_g: 10.6, lif_g: 0 },
    portions: [bardak(330)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Kola, şekersiz',
    per_100g: { kalori: 0, protein_g: 0, yag_g: 0, karbonhidrat_g: 0, lif_g: 0 },
    portions: [bardak(330)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Maden suyu',
    per_100g: { kalori: 0, protein_g: 0, yag_g: 0, karbonhidrat_g: 0, lif_g: 0 },
    portions: [bardak(200)],
    source: 'turkomp',
    verified: true,
  },
  {
    name_tr: 'Enerji içeceği',
    per_100g: { kalori: 44, protein_g: 0, yag_g: 0, karbonhidrat_g: 11, lif_g: 0 },
    portions: [bardak(250)],
    source: 'turkomp',
    verified: true,
  },

  // --- Fırın — kuyruk ---
  {
    name_tr: 'Kruvasan, sade',
    per_100g: { kalori: 403, protein_g: 8, yag_g: 21, karbonhidrat_g: 45.6, lif_g: 2.6 },
    portions: [adet(60)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Kurabiye, tereyağlı',
    per_100g: { kalori: 488, protein_g: 6, yag_g: 24, karbonhidrat_g: 62, lif_g: 1.8 },
    portions: [adet(15), porsiyon(40)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Kek, sade',
    per_100g: { kalori: 406, protein_g: 6, yag_g: 18, karbonhidrat_g: 55, lif_g: 1.2 },
    portions: [dilim(60)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Brownie',
    per_100g: { kalori: 448, protein_g: 6, yag_g: 24, karbonhidrat_g: 52, lif_g: 3 },
    portions: [adet(50)],
    source: 'bizim',
    verified: true,
  },
  {
    name_tr: 'Milföy böreği',
    per_100g: { kalori: 396, protein_g: 7, yag_g: 24, karbonhidrat_g: 38, lif_g: 1.4 },
    portions: [adet(70)],
    source: 'bizim',
    verified: true,
  },

  // --- Atıştırmalık — kuyruk ---
  {
    name_tr: 'Gofret, çikolatalı',
    per_100g: { kalori: 515, protein_g: 6, yag_g: 27, karbonhidrat_g: 62, lif_g: 1.6 },
    portions: [adet(35)],
    source: 'openfoodfacts',
    verified: true,
  },
  {
    name_tr: 'Cips, patates',
    per_100g: { kalori: 544, protein_g: 6.6, yag_g: 34, karbonhidrat_g: 53, lif_g: 4.4 },
    portions: [porsiyon(30)],
    source: 'openfoodfacts',
    verified: true,
  },
  {
    name_tr: 'Cips, mısır',
    per_100g: { kalori: 514, protein_g: 7, yag_g: 26, karbonhidrat_g: 63, lif_g: 5 },
    portions: [porsiyon(30)],
    source: 'openfoodfacts',
    verified: true,
  },
  {
    name_tr: 'Mısır patlağı, yağsız',
    per_100g: { kalori: 384, protein_g: 12, yag_g: 4.5, karbonhidrat_g: 74, lif_g: 14.5 },
    portions: [kase(25)],
    source: 'openfoodfacts',
    verified: true,
  },
  {
    name_tr: 'Jelibon',
    per_100g: { kalori: 334, protein_g: 4, yag_g: 0.2, karbonhidrat_g: 79, lif_g: 0 },
    portions: [porsiyon(30)],
    source: 'openfoodfacts',
    verified: true,
  },

  // --- Zincir — kuyruk ---
  {
    name_tr: 'Sandviç, tavuklu',
    per_100g: { kalori: 220, protein_g: 13, yag_g: 8, karbonhidrat_g: 24, lif_g: 1.8 },
    portions: [adet(220)],
    source: 'zincir',
    verified: true,
  },
  {
    name_tr: 'Sandviç, ton balıklı',
    per_100g: { kalori: 221, protein_g: 12, yag_g: 9, karbonhidrat_g: 23, lif_g: 1.8 },
    portions: [adet(220)],
    source: 'zincir',
    verified: true,
  },
  {
    name_tr: 'Tavuk burger',
    per_100g: { kalori: 268, protein_g: 14, yag_g: 12, karbonhidrat_g: 26, lif_g: 1.6 },
    portions: [adet(200)],
    source: 'zincir',
    verified: true,
  },
  {
    name_tr: 'Tavuk nugget',
    per_100g: { kalori: 267, protein_g: 15, yag_g: 15, karbonhidrat_g: 18, lif_g: 1 },
    portions: [adet(18), porsiyon(100)],
    source: 'zincir',
    verified: true,
  },
  {
    name_tr: 'Noodle, tavuklu',
    per_100g: { kalori: 170, protein_g: 7, yag_g: 6, karbonhidrat_g: 22, lif_g: 1.4 },
    portions: [kase(300)],
    source: 'zincir',
    verified: true,
  },
  {
    name_tr: 'Wrap, tavuklu',
    per_100g: { kalori: 233, protein_g: 13, yag_g: 9, karbonhidrat_g: 25, lif_g: 2 },
    portions: [adet(230)],
    source: 'zincir',
    verified: true,
  },

  // --- Takviye — kuyruk ---
  {
    name_tr: 'Kreatin monohidrat',
    per_100g: { kalori: 0, protein_g: 0, yag_g: 0, karbonhidrat_g: 0, lif_g: 0 },
    portions: [cayKasigi(5)],
    source: 'openfoodfacts',
    verified: true,
  },
  {
    name_tr: 'Kazein protein tozu',
    per_100g: { kalori: 371, protein_g: 78, yag_g: 3, karbonhidrat_g: 8, lif_g: 1 },
    portions: [{ id: 'olcek', ad: '1 ölçek', gram: 30 }],
    source: 'openfoodfacts',
    verified: true,
  },
  {
    name_tr: 'BCAA tozu',
    per_100g: { kalori: 360, protein_g: 90, yag_g: 0, karbonhidrat_g: 0, lif_g: 0 },
    portions: [{ id: 'olcek', ad: '1 ölçek', gram: 10 }],
    source: 'openfoodfacts',
    verified: true,
  },
];
